-- =============================================
-- STORAGE BUCKETS CONFIGURATION
-- =============================================
-- This file documents the storage buckets that need to be created
-- via Supabase Dashboard or CLI. These CANNOT be created via migrations.
--
-- TO CREATE BUCKETS:
-- 1. Via Dashboard: Navigate to Storage > Create Bucket
-- 2. Via CLI: Use the Supabase Management API or Dashboard
-- =============================================

-- =============================================
-- BUCKET CONFIGURATIONS
-- =============================================

-- 1. AVATARS
-- Name: avatars
-- Public: Yes
-- File size limit: 5MB (5242880 bytes)
-- Allowed MIME types: image/jpeg, image/png, image/webp, image/gif

-- 2. LOGOS
-- Name: logos
-- Public: Yes
-- File size limit: 5MB (5242880 bytes)
-- Allowed MIME types: image/jpeg, image/png, image/svg+xml, image/webp

-- 3. DOCUMENTS
-- Name: documents
-- Public: No
-- File size limit: 50MB (52428800 bytes)
-- Allowed MIME types: 
--   - application/pdf
--   - application/msword
--   - application/vnd.openxmlformats-officedocument.wordprocessingml.document
--   - application/vnd.ms-excel
--   - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
--   - application/vnd.ms-powerpoint
--   - application/vnd.openxmlformats-officedocument.presentationml.presentation
--   - text/plain
--   - text/csv

-- 4. MEDIA
-- Name: media
-- Public: No
-- File size limit: 500MB (524288000 bytes)
-- Allowed MIME types:
--   - image/jpeg, image/png, image/webp, image/gif, image/svg+xml
--   - video/mp4, video/quicktime, video/x-msvideo
--   - audio/mpeg, audio/wav, audio/ogg

-- 5. PROJECT-FILES
-- Name: project-files
-- Public: No
-- File size limit: 100MB (104857600 bytes)
-- Allowed MIME types:
--   - application/pdf
--   - application/zip
--   - application/x-zip-compressed
--   - image/jpeg, image/png, image/webp
--   - application/vnd.openxmlformats-officedocument.wordprocessingml.document
--   - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

-- 6. EVENT-ASSETS
-- Name: event-assets
-- Public: No
-- File size limit: 500MB (524288000 bytes)
-- Allowed MIME types:
--   - image/jpeg, image/png, image/webp
--   - video/mp4, video/quicktime
--   - application/pdf

-- 7. TECHNICAL-DRAWINGS
-- Name: technical-drawings
-- Public: No
-- File size limit: 50MB (52428800 bytes)
-- Allowed MIME types:
--   - application/pdf
--   - image/jpeg, image/png
--   - application/vnd.autocad.dwg
--   - image/svg+xml

-- 8. CONTRACTS
-- Name: contracts
-- Public: No
-- File size limit: 50MB (52428800 bytes)
-- Allowed MIME types:
--   - application/pdf
--   - application/msword
--   - application/vnd.openxmlformats-officedocument.wordprocessingml.document

-- 9. REPORTS
-- Name: reports
-- Public: No
-- File size limit: 50MB (52428800 bytes)
-- Allowed MIME types:
--   - application/pdf
--   - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
--   - text/csv

-- 10. RECEIPTS
-- Name: receipts
-- Public: No
-- File size limit: 10MB (10485760 bytes)
-- Allowed MIME types:
--   - application/pdf
--   - image/jpeg, image/png, image/webp

-- 11. INVENTORY-PHOTOS
-- Name: inventory-photos
-- Public: No (workspace-scoped access)
-- File size limit: 10MB per photo (10485760 bytes)
-- Allowed MIME types:
--   - image/jpeg, image/png, image/webp, image/heic
-- Max photos per item: 8 (Sortly standard)
-- Features: Visual inventory tracking, barcode label photos, condition documentation

-- =============================================
-- FOLDER STRUCTURE REFERENCE
-- =============================================

-- avatars/{user_id}/avatar.jpg
-- logos/{organization_id}/logo.png
-- documents/{workspace_id}/contracts/
-- documents/{workspace_id}/riders/
-- documents/{workspace_id}/tech-specs/
-- documents/{workspace_id}/permits/
-- documents/{workspace_id}/insurance/
-- media/{workspace_id}/{production_id}/photos/
-- media/{workspace_id}/{production_id}/videos/
-- media/{workspace_id}/{production_id}/audio/
-- project-files/{workspace_id}/{production_id}/planning/
-- project-files/{workspace_id}/{production_id}/designs/
-- project-files/{workspace_id}/{production_id}/deliverables/
-- event-assets/{workspace_id}/{event_id}/run-of-show/
-- event-assets/{workspace_id}/{event_id}/cue-sheets/
-- event-assets/{workspace_id}/{event_id}/stage-plots/
-- technical-drawings/{workspace_id}/{location_id}/floor-plans/
-- technical-drawings/{workspace_id}/{location_id}/site-maps/
-- technical-drawings/{workspace_id}/{location_id}/cad/
-- contracts/{workspace_id}/vendor/
-- contracts/{workspace_id}/client/
-- contracts/{workspace_id}/employment/
-- reports/{workspace_id}/financial/
-- reports/{workspace_id}/analytics/
-- reports/{workspace_id}/compliance/
-- receipts/{workspace_id}/{expense_report_id}/
-- inventory-photos/{workspace_id}/{inventory_item_id}/photo-{index}.jpg
-- inventory-photos/{workspace_id}/{inventory_item_id}/barcode-label.png
-- inventory-photos/{workspace_id}/{inventory_item_id}/condition-{timestamp}.jpg
