/**
 * Centralized Mock Data for Community Module
 * Used when NEXT_PUBLIC_DEMO_MODE=true
 */

export const mockActivityPosts = [
  {
    id: 'demo-post-1',
    author: { first_name: 'Jessica', last_name: 'Martinez', job_title: 'Stage Manager', avatar_url: null },
    content: 'Just wrapped the most incredible 3-day festival setup! Our crew worked around the clock to build 5 stages from the ground up. The energy, teamwork, and dedication everyone brought was unmatched. 🎪✨',
    created_at: new Date(Date.now() - 3600000).toISOString(),
    likes_count: 234,
    comments_count: 18,
    shares_count: 5,
    tags: ['festival', 'teamwork'],
    media_urls: [],
  },
  {
    id: 'demo-post-2',
    author: { first_name: 'Mike', last_name: 'Thompson', job_title: 'Lighting Technician', avatar_url: null },
    content: 'That moment when the artist walks on stage and your lighting cues hit PERFECTLY. Three weeks of programming, countless rehearsals, and it all comes together in those magical moments. 💡🎭',
    created_at: new Date(Date.now() - 7200000).toISOString(),
    likes_count: 456,
    comments_count: 32,
    shares_count: 12,
    tags: ['lighting', 'showtime'],
    media_urls: [],
  },
  {
    id: 'demo-post-3',
    author: { first_name: 'Sarah', last_name: 'Chen', job_title: 'Audio Engineer', avatar_url: null },
    content: 'Pro tip for new audio engineers: Always, ALWAYS check your phantom power before connecting ribbon mics. Just saved a vintage U47 from potential damage. Small habits make all the difference! 🎤',
    created_at: new Date(Date.now() - 14400000).toISOString(),
    likes_count: 892,
    comments_count: 67,
    shares_count: 143,
    tags: ['audio', 'protip', 'equipment'],
    media_urls: ['/api/placeholder/400/300'],
  },
]

export const mockConnections = [
  {
    id: 'demo-connection-1',
    user_id: 'demo-user-1',
    profile: {
      first_name: 'Alex',
      last_name: 'Rodriguez',
      job_title: 'Lighting Designer',
      location: 'Los Angeles, CA',
      avatar_url: null,
      bio: '15+ years in live event production. Specializing in concert and theater lighting.',
    },
    status: 'connected',
    mutual_connections: 12,
    connected_at: new Date(Date.now() - 7776000000).toISOString(),
  },
  {
    id: 'demo-connection-2',
    user_id: 'demo-user-2',
    profile: {
      first_name: 'Maria',
      last_name: 'Garcia',
      job_title: 'Video Engineer',
      location: 'New York, NY',
      avatar_url: null,
      bio: 'LED wall specialist and video content producer for live events.',
    },
    status: 'connected',
    mutual_connections: 8,
    connected_at: new Date(Date.now() - 12960000000).toISOString(),
  },
  {
    id: 'demo-connection-3',
    user_id: 'demo-user-3',
    profile: {
      first_name: 'James',
      last_name: 'Kim',
      job_title: 'Production Manager',
      location: 'Austin, TX',
      avatar_url: null,
      bio: 'Tour production manager with experience in festivals and corporate events.',
    },
    status: 'pending',
    mutual_connections: 5,
    requested_at: new Date(Date.now() - 604800000).toISOString(),
  },
]

export const mockDiscussions = [
  {
    id: 'demo-discussion-1',
    title: 'Best practices for outdoor festival power distribution?',
    content: 'Planning a 3-day outdoor festival with 5 stages. Looking for advice on power distribution setup and redundancy. What are your go-to strategies?',
    author_id: 'demo-user-4',
    author: {
      name: 'David Brown',
      title: 'Production Electrician',
      avatar_url: null,
    },
    category: 'technical',
    tags: ['power', 'festival', 'outdoor', 'distribution'],
    views: 347,
    replies: 23,
    likes: 45,
    status: 'active',
    created_at: new Date(Date.now() - 1296000000).toISOString(),
    last_activity: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'demo-discussion-2',
    title: 'RF Coordination for 100+ wireless mics - Tools and tips?',
    content: 'Working on a large corporate event with 100+ wireless microphones. What software and workflow do you recommend for frequency coordination?',
    author_id: 'demo-user-5',
    author: {
      name: 'Susan White',
      title: 'RF Coordinator',
      avatar_url: null,
    },
    category: 'audio',
    tags: ['wireless', 'rf', 'coordination', 'microphones'],
    views: 892,
    replies: 34,
    likes: 78,
    status: 'active',
    created_at: new Date(Date.now() - 2592000000).toISOString(),
    last_activity: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'demo-discussion-3',
    title: 'LED wall calibration best practices',
    content: 'What is your process for calibrating large LED walls? Any recommended tools or techniques for color matching across multiple panels?',
    author_id: 'demo-user-6',
    author: {
      name: 'Robert Taylor',
      title: 'Video Engineer',
      avatar_url: null,
    },
    category: 'video',
    tags: ['led', 'calibration', 'video', 'color'],
    views: 456,
    replies: 18,
    likes: 34,
    status: 'active',
    created_at: new Date(Date.now() - 5184000000).toISOString(),
    last_activity: new Date(Date.now() - 86400000).toISOString(),
  },
]

export const mockCommunityEvents = [
  {
    id: 'demo-community-event-1',
    title: 'Virtual Meetup: Lighting Design Trends 2025',
    description: 'Join us for a discussion on the latest trends in lighting design for live events. Share your experiences and learn from industry professionals.',
    type: 'virtual',
    date: new Date(Date.now() + 604800000).toISOString(),
    duration: 90, // minutes
    host_id: 'demo-user-7',
    host: {
      name: 'Lighting Professionals Network',
      avatar_url: null,
    },
    attendees: 127,
    max_attendees: 500,
    category: 'lighting',
    tags: ['lighting', 'design', 'trends', 'virtual'],
    created_at: new Date(Date.now() - 1296000000).toISOString(),
  },
  {
    id: 'demo-community-event-2',
    title: 'NYC Audio Mixer Meetup',
    description: 'Monthly in-person gathering for audio professionals in the NYC area. Network, share knowledge, and discuss industry challenges.',
    type: 'in_person',
    date: new Date(Date.now() + 1209600000).toISOString(),
    duration: 120,
    location: 'Manhattan, NY',
    host_id: 'demo-user-8',
    host: {
      name: 'NYC Audio Engineers Guild',
      avatar_url: null,
    },
    attendees: 34,
    max_attendees: 50,
    category: 'audio',
    tags: ['audio', 'networking', 'nyc', 'meetup'],
    created_at: new Date(Date.now() - 2592000000).toISOString(),
  },
]

export const mockNews = [
  {
    id: 'demo-news-1',
    title: 'New LED Technology Revolutionizes Outdoor Events',
    excerpt: 'Latest LED panel technology offers unprecedented brightness and color accuracy for daylight outdoor productions.',
    content: 'Full article content...',
    author: 'Industry News Team',
    category: 'technology',
    tags: ['led', 'video', 'technology', 'outdoor'],
    image: '/api/placeholder/800/400',
    published_at: new Date(Date.now() - 172800000).toISOString(),
    views: 2341,
  },
  {
    id: 'demo-news-2',
    title: 'OSHA Updates Rigging Safety Requirements',
    excerpt: 'New safety guidelines for entertainment rigging operations now in effect. Here is what you need to know.',
    content: 'Full article content...',
    author: 'Safety & Compliance Team',
    category: 'safety',
    tags: ['safety', 'rigging', 'osha', 'compliance'],
    image: '/api/placeholder/800/400',
    published_at: new Date(Date.now() - 432000000).toISOString(),
    views: 1876,
  },
]

export const mockShowcase = [
  {
    id: 'demo-showcase-1',
    title: 'Coachella 2024 Main Stage Design',
    description: 'Behind the scenes look at the technical design and execution of the Coachella main stage.',
    type: 'project',
    category: 'festival',
    images: ['/api/placeholder/800/600', '/api/placeholder/800/600'],
    author_id: 'demo-user-9',
    author: {
      name: 'Festival Design Studios',
      avatar_url: null,
    },
    likes: 456,
    comments: 34,
    tags: ['festival', 'lighting', 'stage-design'],
    created_at: new Date(Date.now() - 7776000000).toISOString(),
  },
  {
    id: 'demo-showcase-2',
    title: 'Broadway Revival: Technical Innovation',
    description: 'Innovative use of projection mapping and automated rigging in our latest Broadway production.',
    type: 'project',
    category: 'theater',
    images: ['/api/placeholder/800/600'],
    author_id: 'demo-user-10',
    author: {
      name: 'Theater Technical Collective',
      avatar_url: null,
    },
    likes: 234,
    comments: 18,
    tags: ['theater', 'projection', 'automation'],
    created_at: new Date(Date.now() - 12960000000).toISOString(),
  },
]

export const mockStudios = [
  {
    id: 'demo-studio-1',
    name: 'Pro Audio Rentals LA',
    type: 'rental_house',
    description: 'Full-service audio equipment rental specializing in large-format consoles and wireless systems.',
    location: 'Los Angeles, CA',
    services: ['Audio Equipment Rental', 'System Design', 'Technical Support'],
    specialties: ['Concert touring', 'Corporate events', 'Theater'],
    equipment_inventory: 2500,
    rating: 4.9,
    reviews: 234,
    image: '/api/placeholder/400/300',
    contact: {
      email: 'info@proaudiorentalsla.com',
      phone: '+1 (323) 555-0123',
      website: 'https://proaudiorentalsla.com',
    },
  },
  {
    id: 'demo-studio-2',
    name: 'Lighting Design Collective',
    type: 'design_firm',
    description: 'Award-winning lighting design firm for concerts, theater, and special events.',
    location: 'New York, NY',
    services: ['Lighting Design', 'Pre-visualization', 'Programming', 'Project Management'],
    specialties: ['Concert touring', 'Broadway', 'Corporate events'],
    projects_completed: 500,
    rating: 4.8,
    reviews: 156,
    image: '/api/placeholder/400/300',
    contact: {
      email: 'info@ldcollective.com',
      phone: '+1 (212) 555-0456',
      website: 'https://ldcollective.com',
    },
  },
]

export const mockCompetitions = [
  {
    id: 'demo-competition-1',
    title: 'Best Festival Lighting Design 2025',
    description: 'Submit your best festival lighting design work for a chance to win industry recognition and prizes.',
    type: 'design',
    category: 'lighting',
    prize: '$5,000 + Industry Recognition',
    deadline: new Date(Date.now() + 5184000000).toISOString(),
    entries: 67,
    status: 'open',
    organizer: 'Lighting Design Association',
    rules_url: '#',
    created_at: new Date(Date.now() - 7776000000).toISOString(),
  },
  {
    id: 'demo-competition-2',
    title: 'Innovation in Live Event Technology Award',
    description: 'Showcase innovative technical solutions that pushed the boundaries of live event production.',
    type: 'innovation',
    category: 'technology',
    prize: 'Industry Award + Conference Speaking Opportunity',
    deadline: new Date(Date.now() + 10368000000).toISOString(),
    entries: 34,
    status: 'open',
    organizer: 'Event Technology Council',
    rules_url: '#',
    created_at: new Date(Date.now() - 5184000000).toISOString(),
  },
]
