// Mock data for Community Gamification Features (Skool-compatible)

export const mockMemberLevels = [
  {
    id: 'ml-1',
    workspace_id: 'ws-1',
    user_id: 'user-1',
    points: 2500,
    level: 7,
    posts_count: 45,
    comments_count: 123,
    likes_given: 89,
    likes_received: 234,
    badges: ['early_adopter', 'helpful', 'content_creator'],
    rank_position: 1,
    last_active_at: new Date().toISOString(),
  },
  {
    id: 'ml-2',
    workspace_id: 'ws-1',
    user_id: 'user-2',
    points: 850,
    level: 6,
    posts_count: 28,
    comments_count: 67,
    likes_given: 45,
    likes_received: 98,
    badges: ['active_member', 'helpful'],
    rank_position: 2,
    last_active_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'ml-3',
    workspace_id: 'ws-1',
    user_id: 'user-3',
    points: 320,
    level: 5,
    posts_count: 15,
    comments_count: 34,
    likes_given: 23,
    likes_received: 42,
    badges: ['engaged'],
    rank_position: 3,
    last_active_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'ml-4',
    workspace_id: 'ws-1',
    user_id: 'user-4',
    points: 180,
    level: 4,
    posts_count: 12,
    comments_count: 28,
    likes_given: 19,
    likes_received: 31,
    badges: [],
    rank_position: 4,
    last_active_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'ml-5',
    workspace_id: 'ws-1',
    user_id: 'user-5',
    points: 72,
    level: 4,
    posts_count: 8,
    comments_count: 15,
    likes_given: 12,
    likes_received: 18,
    badges: [],
    rank_position: 5,
    last_active_at: new Date(Date.now() - 172800000).toISOString(),
  },
]

export const mockPointTransactions = [
  {
    id: 'pt-1',
    workspace_id: 'ws-1',
    user_id: 'user-1',
    action_type: 'post_liked',
    points_delta: 1,
    points_after: 2500,
    reference_type: 'post',
    reference_id: 'post-123',
    description: 'Your post was liked',
    created_at: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: 'pt-2',
    workspace_id: 'ws-1',
    user_id: 'user-1',
    action_type: 'comment_liked',
    points_delta: 1,
    points_after: 2499,
    reference_type: 'comment',
    reference_id: 'comment-456',
    description: 'Your comment was liked',
    created_at: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'pt-3',
    workspace_id: 'ws-1',
    user_id: 'user-1',
    action_type: 'level_bonus',
    points_delta: 50,
    points_after: 2498,
    reference_type: 'system',
    reference_id: null,
    description: 'Reached Level 7!',
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'pt-4',
    workspace_id: 'ws-1',
    user_id: 'user-1',
    action_type: 'daily_bonus',
    points_delta: 5,
    points_after: 2448,
    reference_type: 'system',
    reference_id: null,
    description: 'Daily login bonus',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'pt-5',
    workspace_id: 'ws-1',
    user_id: 'user-1',
    action_type: 'achievement_unlocked',
    points_delta: 25,
    points_after: 2443,
    reference_type: 'achievement',
    reference_id: 'ach-content-creator',
    description: 'Achievement: Content Creator (50+ posts)',
    created_at: new Date(Date.now() - 172800000).toISOString(),
  },
]

export const mockLeaderboard = mockMemberLevels.map((level: any, index: number) => ({
  ...level,
  first_name: ['Sarah', 'Alex', 'Jordan', 'Taylor', 'Morgan'][index],
  last_name: ['Chen', 'Rivera', 'Patel', 'Kim', 'Santos'][index],
  avatar_url: null,
  current_rank: index + 1,
}))

export const mockLevelConfig = [
  { level: 1, points_required: 0, custom_name: 'Newcomer', custom_icon: '🌱' },
  { level: 2, points_required: 5, custom_name: 'Member', custom_icon: '👋' },
  { level: 3, points_required: 20, custom_name: 'Active', custom_icon: '⭐' },
  { level: 4, points_required: 65, custom_name: 'Contributor', custom_icon: '🎯' },
  { level: 5, points_required: 155, custom_name: 'Expert', custom_icon: '💎' },
  { level: 6, points_required: 500, custom_name: 'Leader', custom_icon: '👑' },
  { level: 7, points_required: 2015, custom_name: 'Champion', custom_icon: '🏆' },
  { level: 8, points_required: 8015, custom_name: 'Master', custom_icon: '🚀' },
  { level: 9, points_required: 33015, custom_name: 'Legend', custom_icon: '⚡' },
]

// Mock community posts with poll support
export const mockCommunityPostsWithPolls = [
  {
    id: 'post-1',
    workspace_id: 'ws-1',
    type: 'activity',
    author_id: 'user-1',
    title: null,
    content: "What's your biggest challenge in production management right now?",
    media_urls: [],
    likes_count: 24,
    comments_count: 12,
    shares_count: 3,
    visibility: 'public',
    tags: ['question', 'discussion'],
    is_featured: false,
    is_sponsored: false,
    poll_options: ['Budget constraints', 'Timeline management', 'Resource allocation', 'Team coordination'],
    poll_votes: {
      option_0: ['user-2', 'user-3', 'user-5'],
      option_1: ['user-4', 'user-6'],
      option_2: ['user-7', 'user-8', 'user-9', 'user-10'],
      option_3: ['user-11', 'user-12'],
    },
    poll_expires_at: new Date(Date.now() + 604800000).toISOString(), // 7 days from now
    poll_allow_multiple: false,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    author: {
      id: 'user-1',
      first_name: 'Sarah',
      last_name: 'Chen',
      avatar_url: null,
      job_title: 'Production Manager',
    },
  },
  {
    id: 'post-2',
    workspace_id: 'ws-1',
    type: 'activity',
    author_id: 'user-2',
    title: null,
    content: 'Just wrapped up a 12-hour shoot day! The team was incredible, and we got every shot we needed. Feeling grateful! 🎬✨',
    media_urls: [],
    likes_count: 45,
    comments_count: 8,
    shares_count: 2,
    visibility: 'public',
    tags: ['milestone', 'grateful'],
    is_featured: false,
    is_sponsored: false,
    poll_options: null,
    poll_votes: null,
    poll_expires_at: null,
    poll_allow_multiple: false,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    author: {
      id: 'user-2',
      first_name: 'Alex',
      last_name: 'Rivera',
      avatar_url: null,
      job_title: 'Director of Photography',
    },
  },
  {
    id: 'post-3',
    workspace_id: 'ws-1',
    type: 'activity',
    author_id: 'user-3',
    title: null,
    content: 'Which collaboration tools do you find most essential? (Select all that apply)',
    media_urls: [],
    likes_count: 18,
    comments_count: 5,
    shares_count: 1,
    visibility: 'public',
    tags: ['tools', 'productivity'],
    is_featured: false,
    is_sponsored: false,
    poll_options: ['Slack/Teams', 'Frame.io', 'Trello/Asana', 'Google Drive', 'Other'],
    poll_votes: {
      option_0: ['user-1', 'user-4', 'user-5', 'user-8'],
      option_1: ['user-2', 'user-6', 'user-7'],
      option_2: ['user-3', 'user-9'],
      option_3: ['user-1', 'user-2', 'user-10'],
      option_4: ['user-11'],
    },
    poll_expires_at: new Date(Date.now() + 259200000).toISOString(), // 3 days from now
    poll_allow_multiple: true,
    created_at: new Date(Date.now() - 10800000).toISOString(),
    author: {
      id: 'user-3',
      first_name: 'Jordan',
      last_name: 'Patel',
      avatar_url: null,
      job_title: 'Producer',
    },
  },
]

// Mock course data with level-gating
export const mockCoursesWithLevels = [
  {
    id: 'course-1',
    title: 'Production Fundamentals',
    description: 'Learn the basics of production management',
    access_level: 'all_members',
    required_level: 1,
    enrollment_count: 234,
    status: 'published',
    thumbnail_url: null,
  },
  {
    id: 'course-2',
    title: 'Advanced Cinematography',
    description: 'Master advanced camera techniques',
    access_level: 'level_based',
    required_level: 3,
    enrollment_count: 89,
    status: 'published',
    thumbnail_url: null,
  },
  {
    id: 'course-3',
    title: 'VFX Pipeline Mastery',
    description: 'Complete VFX workflow from pre to post',
    access_level: 'level_based',
    required_level: 5,
    enrollment_count: 34,
    status: 'published',
    thumbnail_url: null,
  },
  {
    id: 'course-4',
    title: 'Executive Production Course',
    description: 'For seasoned production executives',
    access_level: 'purchase',
    required_level: 1,
    purchase_price: 299.00,
    enrollment_count: 12,
    status: 'published',
    thumbnail_url: null,
  },
]

// Mock course enrollments with progress
export const mockCourseEnrollments = [
  {
    id: 'enroll-1',
    course_id: 'course-1',
    user_id: 'user-1',
    progress_percentage: 100,
    lessons_completed: 12,
    total_lessons: 12,
    status: 'completed',
    enrolled_at: new Date(Date.now() - 2592000000).toISOString(),
    completed_at: new Date(Date.now() - 1296000000).toISOString(),
  },
  {
    id: 'enroll-2',
    course_id: 'course-2',
    user_id: 'user-1',
    progress_percentage: 67,
    lessons_completed: 8,
    total_lessons: 12,
    status: 'active',
    enrolled_at: new Date(Date.now() - 604800000).toISOString(),
    completed_at: null,
  },
  {
    id: 'enroll-3',
    course_id: 'course-3',
    user_id: 'user-1',
    progress_percentage: 25,
    lessons_completed: 3,
    total_lessons: 12,
    status: 'active',
    enrolled_at: new Date(Date.now() - 86400000).toISOString(),
    completed_at: null,
  },
]
