/**
 * Mock Data for Events Module
 */

export const mockEventsCalendar = [
  {
    id: 'demo-event-1',
    title: 'Load-In Day 1',
    description: 'Main stage equipment load-in and setUp',
    start_time: new Date(Date.now() + 4924800000).toISOString(), // 57 days from now
    end_time: new Date(Date.now() + 4953600000).toISOString(),
    all_day: false,
    type: 'setUp',
    status: 'confirmed',
    production_id: 'demo-prod-1',
    production: { name: 'Summer Music Festival 2025' },
    location_id: 'venue-1',
    location: { name: 'Central Park Main Stage' },
    attendees: ['demo-user-1', 'demo-user-2', 'demo-user-4'],
    created_by: 'demo-user-1',
    is_virtual: false,
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-event-2',
    title: 'Technical Rehearsal',
    description: 'Full technical run-through with performers',
    start_time: new Date(Date.now() + 5097600000).toISOString(),
    end_time: new Date(Date.now() + 5119200000).toISOString(),
    all_day: false,
    type: 'rehearsal',
    status: 'confirmed',
    production_id: 'demo-prod-1',
    production: { name: 'Summer Music Festival 2025' },
    location_id: 'venue-1',
    location: { name: 'Central Park Main Stage' },
    attendees: ['demo-user-1', 'demo-user-2', 'demo-user-3', 'demo-user-4'],
    created_by: 'demo-user-1',
    is_virtual: false,
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-event-3',
    title: 'Production Meeting - Corporate Gala',
    description: 'Client meeting to review AV setUp and timeline',
    start_time: new Date(Date.now() + 1728000000).toISOString(),
    end_time: new Date(Date.now() + 1735200000).toISOString(),
    all_day: false,
    type: 'meeting',
    status: 'confirmed',
    production_id: 'demo-prod-2',
    production: { name: 'Corporate Gala 2025' },
    location_id: 'office-1',
    location: { name: 'Conference Room A' },
    attendees: ['demo-user-1', 'demo-user-2'],
    created_by: 'demo-user-2',
    is_virtual: false,
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-event-4',
    title: 'Site Visit - Broadway Theater',
    description: 'Initial venue assessment and load-in planning',
    start_time: new Date(Date.now() + 6048000000).toISOString(),
    end_time: new Date(Date.now() + 6062400000).toISOString(),
    all_day: false,
    type: 'site_visit',
    status: 'tentative',
    production_id: 'demo-prod-3',
    production: { name: 'Theater Revival' },
    location_id: 'venue-2',
    location: { name: 'Broadway Theater' },
    attendees: ['demo-user-1', 'demo-user-3'],
    created_by: 'demo-user-3',
    is_virtual: false,
    workspace_id: 'demo-workspace',
  },
]

export const mockEventTypes = [
  { id: 'setUp', name: 'Setup/Load-In', color: '#f59e0b' },
  { id: 'rehearsal', name: 'Rehearsal', color: '#8b5cf6' },
  { id: 'performance', name: 'Performance', color: '#ef4444' },
  { id: 'meeting', name: 'Meeting', color: '#3b82f6' },
  { id: 'site_visit', name: 'Site Visit', color: '#10b981' },
  { id: 'strike', name: 'Strike/Load-Out', color: '#6b7280' },
]

export const mockVenues = [
  {
    id: 'venue-1',
    name: 'Central Park Main Stage',
    address: 'Central Park, New York, NY 10024',
    type: 'outdoor',
    capacity: 50000,
    contact_name: 'Parks Department',
    contact_phone: '+1 (555) 777-8888',
    notes: 'Outdoor venue, weather-dependent',
  },
  {
    id: 'venue-2',
    name: 'Broadway Theater',
    address: '1234 Broadway, New York, NY 10036',
    type: 'theater',
    capacity: 1500,
    contact_name: 'Venue Manager',
    contact_phone: '+1 (555) 888-9999',
    notes: 'Historic theater with modern technical infrastructure',
  },
  {
    id: 'office-1',
    name: 'Conference Room A',
    address: '789 Office Plaza, Suite 500',
    type: 'meeting_room',
    capacity: 20,
    contact_name: 'Facilities',
    contact_phone: '+1 (555) 999-0000',
    notes: 'Internal meeting space',
  },
]
