/**
 * Mock Data for Locations Module (Venues, Warehouses, Sites)
 */

export const mockLocations = [
  {
    id: 'demo-location-1',
    name: 'Central Park SummerStage',
    type: 'venue',
    subtype: 'outdoor',
    address: '830 5th Ave, New York, NY 10065',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    postal_code: '10065',
    coordinates: {
      lat: 40.7711,
      lng: -73.9711,
    },
    capacity: 5000,
    stage_dimensions: {
      width: 60,
      depth: 40,
      height: 30,
    },
    load_in_info: {
      dock_doors: 2,
      loading_restrictions: 'Height limit 12ft, weight limit 40,000 lbs per truck',
      parking_spaces: 4,
      access_hours: '6:00 AM - 11:00 PM',
    },
    power: {
      available: true,
      type: '3-phase 400A',
      voltage: '208V',
      distro_location: 'Stage Left',
    },
    internet: {
      available: true,
      speed: '1Gbps',
      wifi: true,
    },
    amenities: ['Green rooms', 'Catering area', 'Equipment storage', 'Restrooms'],
    contact: {
      name: 'Venue Manager',
      email: 'venue@summerstage.org',
      phone: '+1 (212) 555-0123',
    },
    images: ['/api/placeholder/800/600', '/api/placeholder/800/600'],
    notes: 'Outdoor venue with weather contingency plan required. Sound curfew at 10 PM.',
    status: 'active',
    rating: 4.7,
    total_events: 145,
    created_at: new Date(Date.now() - 47304000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-location-2',
    name: 'Broadway Theater',
    type: 'venue',
    subtype: 'theater',
    address: '1681 Broadway, New York, NY 10019',
    city: 'New York',
    state: 'NY',
    country: 'USA',
    postal_code: '10019',
    coordinates: {
      lat: 40.7614,
      lng: -73.9822,
    },
    capacity: 1761,
    stage_dimensions: {
      width: 55,
      depth: 50,
      height: 65,
    },
    load_in_info: {
      dock_doors: 1,
      loading_restrictions: 'Street access only, permits required',
      parking_spaces: 0,
      access_hours: '24/7 with advance notice',
    },
    power: {
      available: true,
      type: '3-phase 800A',
      voltage: '208V/120V',
      distro_location: 'Multiple locations',
    },
    internet: {
      available: true,
      speed: '500Mbps',
      wifi: true,
    },
    amenities: ['Orchestra pit', 'Fly system', 'Multiple dressing rooms', 'Wardrobe', 'Scene shop'],
    contact: {
      name: 'Technical Director',
      email: 'td@broadwaytheater.com',
      phone: '+1 (212) 555-0456',
    },
    images: ['/api/placeholder/800/600'],
    notes: 'Historic theater with modern technical infrastructure. Union crew required.',
    status: 'active',
    rating: 4.9,
    total_events: 523,
    created_at: new Date(Date.now() - 63072000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-location-3',
    name: 'Main Equipment Warehouse',
    type: 'warehouse',
    subtype: 'storage',
    address: '1500 Industrial Pkwy, Los Angeles, CA 90021',
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
    postal_code: '90021',
    coordinates: {
      lat: 34.0194,
      lng: -118.2437,
    },
    square_footage: 25000,
    ceiling_height: 24,
    load_in_info: {
      dock_doors: 4,
      loading_restrictions: 'Fork lift available, overhead cranes',
      parking_spaces: 20,
      access_hours: '24/7 with key card',
    },
    power: {
      available: true,
      type: '3-phase 600A',
      voltage: '208V/120V',
      distro_location: 'Multiple drops',
    },
    internet: {
      available: true,
      speed: '1Gbps',
      wifi: true,
    },
    amenities: ['Climate controlled', 'Security system', 'Office space', 'Workshop area', 'Truck parking'],
    contact: {
      name: 'Warehouse Manager',
      email: 'warehouse@production.com',
      phone: '+1 (323) 555-0789',
    },
    images: ['/api/placeholder/800/600'],
    notes: 'Primary storage facility for all production equipment. Inventory management system in place.',
    status: 'active',
    asset_count: 1245,
    utilization: 78,
    created_at: new Date(Date.now() - 94608000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-location-4',
    name: 'Convention Center Main Hall',
    type: 'venue',
    subtype: 'convention_center',
    address: '1201 S Figueroa St, Los Angeles, CA 90015',
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
    postal_code: '90015',
    coordinates: {
      lat: 34.0407,
      lng: -118.2698,
    },
    capacity: 12000,
    square_footage: 54000,
    ceiling_height: 35,
    load_in_info: {
      dock_doors: 8,
      loading_restrictions: 'Advance logistics plan required',
      parking_spaces: 50,
      access_hours: '24/7 during event setUp',
    },
    power: {
      available: true,
      type: '3-phase 1600A',
      voltage: '480V/208V/120V',
      distro_location: 'Multiple locations throughout hall',
    },
    internet: {
      available: true,
      speed: '10Gbps',
      wifi: true,
      fiber: true,
    },
    amenities: [
      'Multiple meeting rooms',
      'Full catering kitchen',
      'Exhibition space',
      'Rigging points',
      'Loading docks',
      'Freight elevators',
    ],
    contact: {
      name: 'Event Services',
      email: 'events@conventtioncenter.com',
      phone: '+1 (213) 555-1234',
    },
    images: ['/api/placeholder/800/600', '/api/placeholder/800/600'],
    notes: 'Large-scale events and exhibitions. In-house AV available. Exclusive catering contract.',
    status: 'active',
    rating: 4.6,
    total_events: 89,
    created_at: new Date(Date.now() - 78912000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-location-5',
    name: 'Rehearsal Studio Complex',
    type: 'rehearsal_space',
    subtype: 'studio',
    address: '456 Music Row, Nashville, TN 37203',
    city: 'Nashville',
    state: 'TN',
    country: 'USA',
    postal_code: '37203',
    coordinates: {
      lat: 36.1515,
      lng: -86.7887,
    },
    rooms: [
      { name: 'Studio A', capacity: 50, square_footage: 2000 },
      { name: 'Studio B', capacity: 30, square_footage: 1200 },
      { name: 'Studio C', capacity: 20, square_footage: 800 },
    ],
    load_in_info: {
      dock_doors: 1,
      loading_restrictions: 'Standard vehicle access',
      parking_spaces: 15,
      access_hours: '8:00 AM - 10:00 PM',
    },
    power: {
      available: true,
      type: 'Single phase 200A per studio',
      voltage: '120V',
      distro_location: 'In each studio',
    },
    internet: {
      available: true,
      speed: '500Mbps',
      wifi: true,
    },
    amenities: ['PA systems', 'Backline storage', 'Lounge area', 'Vending machines', 'Restrooms'],
    contact: {
      name: 'Studio Manager',
      email: 'studios@rehearsalcomplex.com',
      phone: '+1 (615) 555-4567',
    },
    images: ['/api/placeholder/800/600'],
    notes: 'Full rehearsal facilities with equipment rentals available. Hourly and daily rates.',
    status: 'active',
    rating: 4.8,
    total_bookings: 678,
    created_at: new Date(Date.now() - 55296000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
]

export const mockLocationTypes = [
  { id: 'venue', name: 'Venue', icon: 'map-pin', count: 45 },
  { id: 'warehouse', name: 'Warehouse/Storage', icon: 'warehouse', count: 12 },
  { id: 'rehearsal_space', name: 'Rehearsal Space', icon: 'music', count: 18 },
  { id: 'office', name: 'Office', icon: 'building', count: 8 },
  { id: 'site', name: 'Site/Installation', icon: 'map', count: 23 },
]

export const mockLocationBookings = [
  {
    id: 'demo-booking-1',
    location_id: 'demo-location-1',
    location: { name: 'Central Park SummerStage' },
    production_id: 'demo-prod-1',
    production: { name: 'Summer Music Festival 2025' },
    start_date: new Date(Date.now() + 5097600000).toISOString(),
    end_date: new Date(Date.now() + 5443200000).toISOString(),
    status: 'confirmed',
    contact: {
      name: 'John Doe',
      email: 'john.doe@festival.com',
      phone: '+1 (555) 123-4567',
    },
    notes: 'Multi-day festival setUp and performances',
    created_at: new Date(Date.now() - 7776000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-booking-2',
    location_id: 'demo-location-2',
    location: { name: 'Broadway Theater' },
    production_id: 'demo-prod-3',
    production: { name: 'Theater Revival' },
    start_date: new Date(Date.now() + 7776000000).toISOString(),
    end_date: new Date(Date.now() + 15552000000).toISOString(),
    status: 'pending',
    contact: {
      name: 'Bob Wilson',
      email: 'bob.wilson@broadway.com',
      phone: '+1 (555) 987-6543',
    },
    notes: 'Extended run - awaiting contract finalization',
    created_at: new Date(Date.now() - 2592000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
]

export const mockLocationReviews = [
  {
    id: 'demo-review-1',
    location_id: 'demo-location-1',
    reviewer_id: 'demo-user-1',
    reviewer: { name: 'Sarah Johnson', title: 'Production Manager' },
    rating: 5,
    review: 'Excellent venue with professional staff. Load-in was smooth and stage facilities exceeded expectations.',
    pros: ['Great location', 'Helpful staff', 'Good facilities'],
    cons: ['Limited parking'],
    event_date: new Date(Date.now() - 15552000000).toISOString(),
    created_at: new Date(Date.now() - 14256000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-review-2',
    location_id: 'demo-location-2',
    reviewer_id: 'demo-user-2',
    reviewer: { name: 'Mike Rodriguez', title: 'Technical Director' },
    rating: 5,
    review: 'Historic theater with excellent technical infrastructure. Fly system is well-maintained and crew is professional.',
    pros: ['Professional crew', 'Great acoustics', 'Modern tech'],
    cons: ['Street load-in can be challenging'],
    event_date: new Date(Date.now() - 23328000000).toISOString(),
    created_at: new Date(Date.now() - 22032000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
]
