/**
 * Mock Data for Marketplace Module
 */

export const mockMarketplaceListings = [
  {
    id: 'demo-listing-1',
    title: 'Martin MAC Viper Profile - Available for Rent',
    description: 'Professional moving head fixture in excellent condition. Perfect for concerts and theater productions. Includes road case.',
    type: 'rental',
    category: 'lighting',
    price: 350,
    price_unit: 'day',
    condition: 'excellent',
    status: 'available',
    images: ['/api/placeholder/400/300'],
    seller_id: 'demo-user-1',
    seller: {
      name: 'Pro Lighting Rentals',
      rating: 4.9,
      total_rentals: 156,
      verified: true,
    },
    location: 'Los Angeles, CA',
    available_from: new Date(Date.now() + 86400000).toISOString(),
    available_until: new Date(Date.now() + 31536000000).toISOString(),
    minimum_rental: 1,
    delivery_available: true,
    delivery_fee: 150,
    specs: {
      manufacturer: 'Martin Professional',
      model: 'MAC Viper Profile',
      year: 2020,
      weight: '45 lbs',
      power: '1000W',
    },
    created_at: new Date(Date.now() - 2592000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-listing-2',
    title: 'Shure Wireless Microphone System - For Sale',
    description: 'Complete Shure Axient Digital system with 4 handheld and 2 bodypack transmitters. Barely used, like new condition.',
    type: 'sale',
    category: 'audio',
    price: 6500,
    price_unit: 'fixed',
    condition: 'like_new',
    status: 'available',
    images: ['/api/placeholder/400/300'],
    seller_id: 'demo-user-2',
    seller: {
      name: 'Audio Pro Solutions',
      rating: 4.8,
      total_sales: 89,
      verified: true,
    },
    location: 'New York, NY',
    negotiable: true,
    shipping_included: false,
    shipping_cost: 75,
    specs: {
      manufacturer: 'Shure',
      model: 'Axient Digital ADX5D',
      year: 2022,
      includes: '4 handheld, 2 bodypack, antennas, cables',
    },
    created_at: new Date(Date.now() - 1296000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-listing-3',
    title: 'LED Video Wall Panels - 100 Panels Available',
    description: 'ROE Visual CB5 LED panels. Indoor/outdoor rated, 500x500mm, 5mm pixel pitch. Excellent for events and installations.',
    type: 'rental',
    category: 'video',
    price: 125,
    price_unit: 'day',
    condition: 'good',
    status: 'available',
    images: ['/api/placeholder/400/300'],
    seller_id: 'demo-user-3',
    seller: {
      name: 'Visual Productions Inc',
      rating: 4.7,
      total_rentals: 234,
      verified: true,
    },
    location: 'Austin, TX',
    quantity_available: 100,
    available_from: new Date(Date.now() + 604800000).toISOString(),
    available_until: new Date(Date.now() + 15552000000).toISOString(),
    minimum_rental: 3,
    delivery_available: true,
    installation_available: true,
    specs: {
      manufacturer: 'ROE Visual',
      model: 'Black Pearl CB5',
      pixel_pitch: '5mm',
      panel_size: '500x500mm',
      brightness: '5000 nits',
    },
    created_at: new Date(Date.now() - 5184000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-listing-4',
    title: 'Motor Chain Hoist - 2 Ton Capacity',
    description: 'CM Lodestar electric chain hoist, 2-ton capacity, 20ft lift. Recently inspected and certified.',
    type: 'sale',
    category: 'rigging',
    price: 3200,
    price_unit: 'fixed',
    condition: 'good',
    status: 'available',
    images: ['/api/placeholder/400/300'],
    seller_id: 'demo-user-4',
    seller: {
      name: 'Rigging Solutions LLC',
      rating: 4.9,
      total_sales: 67,
      verified: true,
    },
    location: 'Nashville, TN',
    negotiable: false,
    shipping_included: true,
    includes_certification: true,
    last_inspection: new Date(Date.now() - 2592000000).toISOString(),
    specs: {
      manufacturer: 'CM Lodestar',
      capacity: '2 ton (4000 lbs)',
      lift_height: '20 ft',
      speed: '8 fpm',
      voltage: '120V',
    },
    created_at: new Date(Date.now() - 7776000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
]

export const mockMarketplaceCategories = [
  { id: 'lighting', name: 'Lighting Equipment', count: 342 },
  { id: 'audio', name: 'Audio Equipment', count: 567 },
  { id: 'video', name: 'Video Equipment', count: 234 },
  { id: 'rigging', name: 'Rigging & Staging', count: 189 },
  { id: 'power', name: 'Power Distribution', count: 145 },
  { id: 'cables', name: 'Cables & Adapters', count: 456 },
  { id: 'cases', name: 'Cases & Transport', count: 278 },
  { id: 'other', name: 'Other Equipment', count: 123 },
]

export const mockMarketplaceRequests = [
  {
    id: 'demo-request-1',
    title: 'Looking for DiGiCo SD10 Console',
    description: 'Need DiGiCo SD10 for 2-week festival tour in July. Must include stage rack and fiber optic.',
    type: 'rental',
    category: 'audio',
    budget: 5000,
    budget_unit: 'total',
    needed_from: new Date(Date.now() + 7776000000).toISOString(),
    needed_until: new Date(Date.now() + 8985600000).toISOString(),
    location: 'Multiple US Cities',
    status: 'active',
    responses: 7,
    requester_id: 'demo-user-5',
    requester: {
      name: 'Festival Sound Inc',
      rating: 4.8,
      verified: true,
    },
    created_at: new Date(Date.now() - 604800000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-request-2',
    title: 'Seeking Grandma3 Lighting Console to Purchase',
    description: 'Looking to buy used Grandma3 Full-size console in good working condition. Willing to pay fair market price.',
    type: 'purchase',
    category: 'lighting',
    budget: 35000,
    budget_unit: 'fixed',
    negotiable: true,
    location: 'Anywhere in US',
    status: 'active',
    responses: 3,
    requester_id: 'demo-user-6',
    requester: {
      name: 'Touring Productions Co',
      rating: 4.9,
      verified: true,
    },
    created_at: new Date(Date.now() - 1209600000).toISOString(),
    workspace_id: 'demo-workspace',
  },
]

export const mockMarketplaceTransactions = [
  {
    id: 'demo-transaction-1',
    listing_id: 'demo-listing-1',
    listing_title: 'Martin MAC Viper Profile',
    buyer_id: 'demo-user-7',
    buyer: { name: 'Corporate Events Ltd' },
    seller_id: 'demo-user-1',
    seller: { name: 'Pro Lighting Rentals' },
    type: 'rental',
    start_date: new Date(Date.now() + 2592000000).toISOString(),
    end_date: new Date(Date.now() + 3196800000).toISOString(),
    days: 7,
    price_per_unit: 350,
    quantity: 6,
    subtotal: 14700,
    delivery_fee: 150,
    service_fee: 735,
    total: 15585,
    status: 'confirmed',
    payment_status: 'paid',
    created_at: new Date(Date.now() - 432000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-transaction-2',
    listing_id: 'demo-listing-2',
    listing_title: 'Shure Wireless Microphone System',
    buyer_id: 'demo-user-8',
    buyer: { name: 'Theater Production Co' },
    seller_id: 'demo-user-2',
    seller: { name: 'Audio Pro Solutions' },
    type: 'sale',
    price: 6500,
    shipping_cost: 75,
    service_fee: 325,
    total: 6900,
    status: 'completed',
    payment_status: 'paid',
    shipped_at: new Date(Date.now() - 259200000).toISOString(),
    delivered_at: new Date(Date.now() - 86400000).toISOString(),
    created_at: new Date(Date.now() - 604800000).toISOString(),
    workspace_id: 'demo-workspace',
  },
]
