/**
 * Mock Data for Resources Module (Knowledge Base, Documents, Templates)
 */

export const mockResourceArticles = [
  {
    id: 'demo-article-1',
    title: 'Complete Guide to Load-In Planning',
    slug: 'complete-guide-to-load-in-planning',
    description: 'A comprehensive guide covering best practices for efficient load-in operations, from advance planning to crew coordination.',
    content: 'Full article content would go here...',
    category: 'best_practices',
    tags: ['load-in', 'logistics', 'planning', 'crew-management'],
    author_id: 'demo-user-1',
    author: {
      name: 'Sarah Johnson',
      title: 'Production Manager',
      avatar_url: null,
    },
    status: 'published',
    views: 1247,
    likes: 89,
    comments_count: 23,
    read_time: 12, // minutes
    featured: true,
    published_at: new Date(Date.now() - 7776000000).toISOString(),
    updated_at: new Date(Date.now() - 2592000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-article-2',
    title: 'Safety Protocols for Rigging Operations',
    slug: 'safety-protocols-for-rigging-operations',
    description: 'Essential safety guidelines and checklists for rigging teams working on live events.',
    content: 'Full article content would go here...',
    category: 'safety',
    tags: ['rigging', 'safety', 'protocols', 'certification'],
    author_id: 'demo-user-2',
    author: {
      name: 'Mike Rodriguez',
      title: 'Head Rigger',
      avatar_url: null,
    },
    status: 'published',
    views: 2341,
    likes: 156,
    comments_count: 45,
    read_time: 8,
    featured: true,
    published_at: new Date(Date.now() - 12960000000).toISOString(),
    updated_at: new Date(Date.now() - 5184000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-article-3',
    title: 'Wireless Microphone Frequency Coordination 101',
    slug: 'wireless-microphone-frequency-coordination-101',
    description: 'Learn the fundamentals of RF coordination for wireless microphone systems in complex environments.',
    content: 'Full article content would go here...',
    category: 'technical',
    tags: ['audio', 'wireless', 'rf', 'coordination'],
    author_id: 'demo-user-3',
    author: {
      name: 'Alex Chen',
      title: 'Audio Engineer',
      avatar_url: null,
    },
    status: 'published',
    views: 892,
    likes: 67,
    comments_count: 18,
    read_time: 15,
    featured: false,
    published_at: new Date(Date.now() - 5184000000).toISOString(),
    updated_at: new Date(Date.now() - 1296000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
]

export const mockResourceCategories = [
  { id: 'best_practices', name: 'Best Practices', count: 45, icon: 'lightbulb' },
  { id: 'safety', name: 'Safety & Compliance', count: 67, icon: 'shield' },
  { id: 'technical', name: 'Technical Guides', count: 89, icon: 'settings' },
  { id: 'workflows', name: 'Workflows & Processes', count: 34, icon: 'workflow' },
  { id: 'equipment', name: 'Equipment Guides', count: 123, icon: 'package' },
  { id: 'case_studies', name: 'Case Studies', count: 28, icon: 'book' },
]

export const mockResourceTemplates = [
  {
    id: 'demo-template-1',
    name: 'Production Schedule Template',
    description: 'Comprehensive production schedule template with all key milestones and deliverables',
    type: 'spreadsheet',
    category: 'planning',
    file_type: 'xlsx',
    file_size: 145000,
    thumbnail: '/api/placeholder/200/150',
    downloads: 456,
    rating: 4.8,
    author_id: 'demo-user-1',
    author: { name: 'Sarah Johnson' },
    tags: ['schedule', 'planning', 'timeline', 'production'],
    created_at: new Date(Date.now() - 15552000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-template-2',
    name: 'Equipment Rental Agreement',
    description: 'Standard rental agreement template covering terms, conditions, insurance, and liability',
    type: 'document',
    category: 'legal',
    file_type: 'docx',
    file_size: 87000,
    thumbnail: '/api/placeholder/200/150',
    downloads: 789,
    rating: 4.9,
    author_id: 'demo-user-2',
    author: { name: 'Legal Team' },
    tags: ['legal', 'rental', 'contract', 'agreement'],
    created_at: new Date(Date.now() - 23328000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-template-3',
    name: 'Load-In Checklist',
    description: 'Detailed checklist for venue load-in covering all departments and phases',
    type: 'checklist',
    category: 'operations',
    file_type: 'pdf',
    file_size: 34000,
    thumbnail: '/api/placeholder/200/150',
    downloads: 1234,
    rating: 4.7,
    author_id: 'demo-user-3',
    author: { name: 'Operations Manager' },
    tags: ['load-in', 'checklist', 'venue', 'operations'],
    created_at: new Date(Date.now() - 18144000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-template-4',
    name: 'Budget Breakdown Template',
    description: 'Comprehensive production budget template with line items and tracking',
    type: 'spreadsheet',
    category: 'financial',
    file_type: 'xlsx',
    file_size: 234000,
    thumbnail: '/api/placeholder/200/150',
    downloads: 567,
    rating: 4.8,
    author_id: 'demo-user-4',
    author: { name: 'Finance Team' },
    tags: ['budget', 'financial', 'planning', 'tracking'],
    created_at: new Date(Date.now() - 12960000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
]

export const mockResourceTutorials = [
  {
    id: 'demo-tutorial-1',
    title: 'How to Use the Production Dashboard',
    description: 'Step-by-step walkthrough of the production dashboard features',
    type: 'video',
    duration: 480, // seconds
    thumbnail: '/api/placeholder/400/225',
    video_url: '#',
    category: 'platform',
    difficulty: 'beginner',
    views: 3421,
    likes: 234,
    author_id: 'demo-user-1',
    author: { name: 'Platform Team' },
    created_at: new Date(Date.now() - 8640000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
  {
    id: 'demo-tutorial-2',
    title: 'Advanced Asset Tracking Techniques',
    description: 'Learn advanced features for managing equipment inventory and tracking',
    type: 'video',
    duration: 720,
    thumbnail: '/api/placeholder/400/225',
    video_url: '#',
    category: 'assets',
    difficulty: 'advanced',
    views: 1876,
    likes: 145,
    author_id: 'demo-user-2',
    author: { name: 'Platform Team' },
    created_at: new Date(Date.now() - 6048000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
]

export const mockResourceGuides = [
  {
    id: 'demo-guide-1',
    title: 'Event Production Fundamentals',
    description: 'Complete guide covering the basics of live event production',
    type: 'course',
    chapters: 12,
    lessons: 45,
    total_duration: 14400, // seconds
    difficulty: 'beginner',
    thumbnail: '/api/placeholder/300/200',
    enrolled: 234,
    rating: 4.9,
    author_id: 'demo-user-1',
    author: { name: 'Education Team' },
    created_at: new Date(Date.now() - 31536000000).toISOString(),
    workspace_id: 'demo-workspace',
  },
]

export const mockResourceDownloads = [
  {
    id: 'demo-download-1',
    resource_id: 'demo-template-1',
    resource_title: 'Production Schedule Template',
    user_id: 'demo-user-5',
    downloaded_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'demo-download-2',
    resource_id: 'demo-template-3',
    resource_title: 'Load-In Checklist',
    user_id: 'demo-user-5',
    downloaded_at: new Date(Date.now() - 172800000).toISOString(),
  },
]
