import type { CountryConfig } from '@/types/country'

export const countries: Record<string, CountryConfig> = {
  US: {
    name: 'United States',
    code: 'US',
    region: 'North America',
    flag: '🇺🇸',
    currency: 'USD',
    language: 'en',
    alternativeLanguages: ['es', 'zh', 'vi', 'ko', 'fr'],
    taxSystem: 'sales_tax',
    taxRates: {
      federal: 0,
      state: {
        CA: 0.0725, NY: 0.04, TX: 0.0625, FL: 0.06, IL: 0.0625,
        PA: 0.06, OH: 0.0575, GA: 0.04, NC: 0.0475, MI: 0.06
      }
    },
    taxInclusive: false,
    dateFormat: 'MM/DD/YYYY',
    timeFormat: '12h',
    measurementSystem: 'imperial',
    phoneFormat: '+1 (XXX) XXX-XXXX',
    addressFormat: {
      line1: 'Street Address',
      line2: 'Apt/Suite (optional)',
      city: 'City',
      state: 'State',
      postalCode: 'ZIP Code',
      postalCodePattern: '^\\d{5}(-\\d{4})?$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: true,
      ageRestriction: 13,
      cookieConsent: 'optional',
      dataResidency: 'US',
      allowedPaymentMethods: ['card', 'paypal', 'apple_pay', 'google_pay', 'ach'],
      shippingRestrictions: [],
      businessHoursTimezone: 'America/New_York'
    }
  },
  GB: {
    name: 'United Kingdom',
    code: 'GB',
    region: 'Europe',
    flag: '🇬🇧',
    currency: 'GBP',
    language: 'en',
    alternativeLanguages: ['pl', 'ur', 'bn'],
    taxSystem: 'vat',
    taxRates: { standard: 0.20, reduced: 0.05, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+44 XXXX XXXXXX',
    addressFormat: {
      line1: 'Address Line 1',
      line2: 'Address Line 2 (optional)',
      city: 'Town/City',
      state: 'County (optional)',
      postalCode: 'Postcode',
      postalCodePattern: '^[A-Z]{1,2}\\d{1,2}[A-Z]?\\s?\\d[A-Z]{2}$'
    },
    compliance: {
      gdprRequired: true,
      ccpaRequired: false,
      ageRestriction: 13,
      cookieConsent: 'required',
      dataResidency: 'EU',
      allowedPaymentMethods: ['card', 'paypal', 'apple_pay', 'google_pay', 'bank_transfer'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Europe/London'
    }
  },
  CA: {
    name: 'Canada',
    code: 'CA',
    region: 'North America',
    flag: '🇨🇦',
    currency: 'CAD',
    language: 'en',
    alternativeLanguages: ['fr', 'zh', 'hi', 'es'],
    taxSystem: 'gst_pst',
    taxRates: {
      federal: 0.05,
      provincial: {
        ON: 0.08, QC: 0.09975, BC: 0.07, AB: 0, MB: 0.07,
        SK: 0.06, NS: 0.10, NB: 0.10, NL: 0.10, PE: 0.10
      }
    },
    taxInclusive: false,
    dateFormat: 'YYYY-MM-DD',
    timeFormat: '12h',
    measurementSystem: 'metric',
    phoneFormat: '+1 (XXX) XXX-XXXX',
    addressFormat: {
      line1: 'Street Address',
      line2: 'Unit/Apt (optional)',
      city: 'City',
      state: 'Province',
      postalCode: 'Postal Code',
      postalCodePattern: '^[A-Z]\\d[A-Z]\\s?\\d[A-Z]\\d$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      pipedaRequired: true,
      ageRestriction: 13,
      cookieConsent: 'optional',
      dataResidency: 'CA',
      allowedPaymentMethods: ['card', 'paypal', 'apple_pay', 'google_pay', 'interac'],
      shippingRestrictions: [],
      businessHoursTimezone: 'America/Toronto'
    }
  },
  DE: {
    name: 'Germany',
    code: 'DE',
    region: 'Europe',
    flag: '🇩🇪',
    currency: 'EUR',
    language: 'de',
    alternativeLanguages: ['en', 'tr', 'ru'],
    taxSystem: 'vat',
    taxRates: { standard: 0.19, reduced: 0.07, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD.MM.YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+49 XXX XXXXXXX',
    addressFormat: {
      line1: 'Straße und Hausnummer',
      line2: 'Adresszusatz (optional)',
      city: 'Stadt',
      state: 'Bundesland (optional)',
      postalCode: 'Postleitzahl',
      postalCodePattern: '^\\d{5}$'
    },
    compliance: {
      gdprRequired: true,
      ccpaRequired: false,
      ageRestriction: 16,
      cookieConsent: 'required',
      dataResidency: 'EU',
      allowedPaymentMethods: ['card', 'paypal', 'apple_pay', 'google_pay', 'sepa', 'sofort'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Europe/Berlin'
    }
  },
  FR: {
    name: 'France',
    code: 'FR',
    region: 'Europe',
    flag: '🇫🇷',
    currency: 'EUR',
    language: 'fr',
    alternativeLanguages: ['en', 'ar', 'es'],
    taxSystem: 'vat',
    taxRates: { standard: 0.20, reduced: 0.055, intermediate: 0.10, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+33 X XX XX XX XX',
    addressFormat: {
      line1: 'Numéro et nom de rue',
      line2: 'Complément d\'adresse (optionnel)',
      city: 'Ville',
      state: 'Région (optionnel)',
      postalCode: 'Code postal',
      postalCodePattern: '^\\d{5}$'
    },
    compliance: {
      gdprRequired: true,
      ccpaRequired: false,
      ageRestriction: 15,
      cookieConsent: 'required',
      dataResidency: 'EU',
      allowedPaymentMethods: ['card', 'paypal', 'apple_pay', 'google_pay', 'sepa'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Europe/Paris'
    }
  },
  AU: {
    name: 'Australia',
    code: 'AU',
    region: 'Oceania',
    flag: '🇦🇺',
    currency: 'AUD',
    language: 'en',
    alternativeLanguages: ['zh', 'vi', 'ar', 'it'],
    taxSystem: 'gst',
    taxRates: { standard: 0.10, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '12h',
    measurementSystem: 'metric',
    phoneFormat: '+61 X XXXX XXXX',
    addressFormat: {
      line1: 'Street Address',
      line2: 'Unit/Apt (optional)',
      city: 'Suburb',
      state: 'State',
      postalCode: 'Postcode',
      postalCodePattern: '^\\d{4}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      privacyActRequired: true,
      ageRestriction: 13,
      cookieConsent: 'optional',
      dataResidency: 'AU',
      allowedPaymentMethods: ['card', 'paypal', 'apple_pay', 'google_pay', 'bpay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Australia/Sydney'
    }
  },
  IN: {
    name: 'India',
    code: 'IN',
    region: 'Asia',
    flag: '🇮🇳',
    currency: 'INR',
    language: 'hi',
    alternativeLanguages: ['en', 'bn', 'te', 'mr', 'ta', 'ur'],
    taxSystem: 'gst',
    taxRates: { standard: 0.18, reduced: 0.05, intermediate: 0.12, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '12h',
    measurementSystem: 'metric',
    phoneFormat: '+91 XXXXX XXXXX',
    addressFormat: {
      line1: 'House/Building No., Street',
      line2: 'Locality/Area (optional)',
      city: 'City',
      state: 'State',
      postalCode: 'PIN Code',
      postalCodePattern: '^\\d{6}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      dpdpaRequired: true,
      ageRestriction: 18,
      cookieConsent: 'optional',
      dataResidency: 'IN',
      allowedPaymentMethods: ['card', 'upi', 'netbanking', 'paytm', 'google_pay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Asia/Kolkata'
    }
  },
  JP: {
    name: 'Japan',
    code: 'JP',
    region: 'Asia',
    flag: '🇯🇵',
    currency: 'JPY',
    language: 'ja',
    alternativeLanguages: ['en'],
    taxSystem: 'consumption_tax',
    taxRates: { standard: 0.10, reduced: 0.08, zero: 0 },
    taxInclusive: true,
    dateFormat: 'YYYY/MM/DD',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+81 XX XXXX XXXX',
    addressFormat: {
      line1: 'Building, Room Number',
      line2: 'Street Address',
      city: 'City/Ward',
      state: 'Prefecture',
      postalCode: 'Postal Code',
      postalCodePattern: '^\\d{3}-\\d{4}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      appiRequired: true,
      ageRestriction: 13,
      cookieConsent: 'optional',
      dataResidency: 'JP',
      allowedPaymentMethods: ['card', 'konbini', 'bank_transfer', 'paypay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Asia/Tokyo'
    }
  },
  BR: {
    name: 'Brazil',
    code: 'BR',
    region: 'South America',
    flag: '🇧🇷',
    currency: 'BRL',
    language: 'pt',
    alternativeLanguages: ['en', 'es'],
    taxSystem: 'complex',
    taxRates: { federal: 0.165, municipal: 0.05 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+55 (XX) XXXXX-XXXX',
    addressFormat: {
      line1: 'Rua, Número',
      line2: 'Complemento (opcional)',
      city: 'Cidade',
      state: 'Estado',
      postalCode: 'CEP',
      postalCodePattern: '^\\d{5}-\\d{3}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      lgpdRequired: true,
      ageRestriction: 18,
      cookieConsent: 'required',
      dataResidency: 'BR',
      allowedPaymentMethods: ['card', 'pix', 'boleto', 'paypal'],
      shippingRestrictions: [],
      businessHoursTimezone: 'America/Sao_Paulo'
    }
  },
  MX: {
    name: 'Mexico',
    code: 'MX',
    region: 'North America',
    flag: '🇲🇽',
    currency: 'MXN',
    language: 'es',
    alternativeLanguages: ['en'],
    taxSystem: 'iva',
    taxRates: { standard: 0.16, border: 0.08, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '12h',
    measurementSystem: 'metric',
    phoneFormat: '+52 XX XXXX XXXX',
    addressFormat: {
      line1: 'Calle y Número',
      line2: 'Colonia',
      city: 'Ciudad',
      state: 'Estado',
      postalCode: 'Código Postal',
      postalCodePattern: '^\\d{5}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      lfpdpppRequired: true,
      ageRestriction: 18,
      cookieConsent: 'optional',
      dataResidency: 'MX',
      allowedPaymentMethods: ['card', 'oxxo', 'spei', 'paypal'],
      shippingRestrictions: [],
      businessHoursTimezone: 'America/Mexico_City'
    }
  },
  NO: {
    name: 'Norway',
    code: 'NO',
    region: 'Europe',
    flag: '🇳🇴',
    currency: 'NOK',
    language: 'no',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.25, reduced: 0.15, low: 0.12, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD.MM.YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+47 XXX XX XXX',
    addressFormat: {
      line1: 'Gate og nummer',
      line2: 'Tillegg (valgfritt)',
      city: 'By',
      state: 'Fylke (valgfritt)',
      postalCode: 'Postnummer',
      postalCodePattern: '^\\d{4}$'
    },
    compliance: {
      gdprRequired: true,
      ccpaRequired: false,
      ageRestriction: 13,
      cookieConsent: 'required',
      dataResidency: 'EU',
      allowedPaymentMethods: ['card', 'vipps', 'paypal', 'apple_pay', 'google_pay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Europe/Oslo'
    }
  },
  ES: {
    name: 'Spain',
    code: 'ES',
    region: 'Europe',
    flag: '🇪🇸',
    currency: 'EUR',
    language: 'es',
    alternativeLanguages: ['en', 'es'],
    taxSystem: 'vat',
    taxRates: { standard: 0.21, reduced: 0.10, superReduced: 0.04, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+34 XXX XXX XXX',
    addressFormat: {
      line1: 'Calle y número',
      line2: 'Piso/Puerta (opcional)',
      city: 'Ciudad',
      state: 'Provincia',
      postalCode: 'Código Postal',
      postalCodePattern: '^\\d{5}$'
    },
    compliance: {
      gdprRequired: true,
      ccpaRequired: false,
      ageRestriction: 14,
      cookieConsent: 'required',
      dataResidency: 'EU',
      allowedPaymentMethods: ['card', 'paypal', 'apple_pay', 'google_pay', 'bizum'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Europe/Madrid'
    }
  },
  SG: {
    name: 'Singapore',
    code: 'SG',
    region: 'Asia',
    flag: '🇸🇬',
    currency: 'SGD',
    language: 'en',
    alternativeLanguages: ['zh', 'id', 'ta'],
    taxSystem: 'gst',
    taxRates: { standard: 0.08, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '12h',
    measurementSystem: 'metric',
    phoneFormat: '+65 XXXX XXXX',
    addressFormat: {
      line1: 'Block/Street',
      line2: 'Unit Number',
      city: 'Singapore',
      state: '',
      postalCode: 'Postal Code',
      postalCodePattern: '^\\d{6}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      pdpaRequired: true,
      ageRestriction: 13,
      cookieConsent: 'optional',
      dataResidency: 'SG',
      allowedPaymentMethods: ['card', 'paynow', 'grabpay', 'paypal', 'apple_pay', 'google_pay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Asia/Singapore'
    }
  },
  KR: {
    name: 'South Korea',
    code: 'KR',
    region: 'Asia',
    flag: '🇰🇷',
    currency: 'KRW',
    language: 'ko',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.10, zero: 0 },
    taxInclusive: true,
    dateFormat: 'YYYY.MM.DD',
    timeFormat: '12h',
    measurementSystem: 'metric',
    phoneFormat: '+82 XX XXXX XXXX',
    addressFormat: {
      line1: '도로명 주소',
      line2: '상세 주소 (선택)',
      city: '시/군/구',
      state: '시/도',
      postalCode: '우편번호',
      postalCodePattern: '^\\d{5}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      pipaRequired: true,
      ageRestriction: 14,
      cookieConsent: 'required',
      dataResidency: 'KR',
      allowedPaymentMethods: ['card', 'kakaopay', 'naverpay', 'payco', 'samsung_pay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Asia/Seoul'
    }
  },
  AE: {
    name: 'United Arab Emirates',
    code: 'AE',
    region: 'Middle East',
    flag: '🇦🇪',
    currency: 'AED',
    language: 'ar',
    alternativeLanguages: ['en', 'ur', 'hi'],
    taxSystem: 'vat',
    taxRates: { standard: 0.05, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '12h',
    measurementSystem: 'metric',
    phoneFormat: '+971 XX XXX XXXX',
    addressFormat: {
      line1: 'Building/Villa',
      line2: 'Street/Area',
      city: 'City',
      state: 'Emirate',
      postalCode: 'P.O. Box (optional)',
      postalCodePattern: '^\\d{5}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      difcRequired: true,
      ageRestriction: 13,
      cookieConsent: 'optional',
      dataResidency: 'AE',
      allowedPaymentMethods: ['card', 'apple_pay', 'google_pay', 'samsung_pay', 'paypal'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Asia/Dubai'
    }
  },
  CN: {
    name: 'China',
    code: 'CN',
    region: 'Asia',
    flag: '🇨🇳',
    currency: 'CNY',
    language: 'zh',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.13, reduced: 0.09, low: 0.06, zero: 0 },
    taxInclusive: true,
    dateFormat: 'YYYY/MM/DD',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+86 XXX XXXX XXXX',
    addressFormat: {
      line1: '省/直辖市',
      line2: '市/区',
      city: '街道/门牌号',
      state: '省份',
      postalCode: '邮政编码',
      postalCodePattern: '^\\d{6}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      piplRequired: true,
      ageRestriction: 14,
      cookieConsent: 'required',
      dataResidency: 'CN',
      allowedPaymentMethods: ['alipay', 'wechat_pay', 'unionpay', 'card'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Asia/Shanghai'
    }
  },
  RU: {
    name: 'Russia',
    code: 'RU',
    region: 'Europe',
    flag: '🇷🇺',
    currency: 'RUB',
    language: 'ru',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.20, reduced: 0.10, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD.MM.YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+7 XXX XXX-XX-XX',
    addressFormat: {
      line1: 'Улица и номер дома',
      line2: 'Квартира (необязательно)',
      city: 'Город',
      state: 'Регион',
      postalCode: 'Индекс',
      postalCodePattern: '^\\d{6}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      fzRequired: true,
      ageRestriction: 18,
      cookieConsent: 'required',
      dataResidency: 'RU',
      allowedPaymentMethods: ['card', 'yandex_money', 'qiwi', 'webmoney'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Europe/Moscow'
    }
  },
  ID: {
    name: 'Indonesia',
    code: 'ID',
    region: 'Asia',
    flag: '🇮🇩',
    currency: 'IDR',
    language: 'en',
    alternativeLanguages: ['id'],
    taxSystem: 'vat',
    taxRates: { standard: 0.11, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+62 XXX XXXX XXXX',
    addressFormat: {
      line1: 'Jalan dan Nomor',
      line2: 'RT/RW (opsional)',
      city: 'Kota/Kabupaten',
      state: 'Provinsi',
      postalCode: 'Kode Pos',
      postalCodePattern: '^\\d{5}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      pdpRequired: true,
      ageRestriction: 17,
      cookieConsent: 'optional',
      dataResidency: 'ID',
      allowedPaymentMethods: ['card', 'gopay', 'ovo', 'dana', 'shopeepay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Asia/Jakarta'
    }
  },
  TR: {
    name: 'Turkey',
    code: 'TR',
    region: 'Europe',
    flag: '🇹🇷',
    currency: 'TRY',
    language: 'tr',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.18, reduced: 0.08, low: 0.01, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD.MM.YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+90 XXX XXX XX XX',
    addressFormat: {
      line1: 'Sokak ve Numara',
      line2: 'Daire (isteğe bağlı)',
      city: 'İlçe',
      state: 'İl',
      postalCode: 'Posta Kodu',
      postalCodePattern: '^\\d{5}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      kvkkRequired: true,
      ageRestriction: 18,
      cookieConsent: 'required',
      dataResidency: 'TR',
      allowedPaymentMethods: ['card', 'paypal', 'apple_pay', 'google_pay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Europe/Istanbul'
    }
  },
  TW: {
    name: 'Taiwan',
    code: 'TW',
    region: 'Asia',
    flag: '🇹🇼',
    currency: 'TWD',
    language: 'zh',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.05, zero: 0 },
    taxInclusive: true,
    dateFormat: 'YYYY/MM/DD',
    timeFormat: '12h',
    measurementSystem: 'metric',
    phoneFormat: '+886 X XXXX XXXX',
    addressFormat: {
      line1: '縣市',
      line2: '鄉鎮市區',
      city: '路街巷弄號',
      state: '縣市',
      postalCode: '郵遞區號',
      postalCodePattern: '^\\d{5}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      pdpaRequired: true,
      ageRestriction: 12,
      cookieConsent: 'optional',
      dataResidency: 'TW',
      allowedPaymentMethods: ['card', 'line_pay', 'jko_pay', 'apple_pay', 'google_pay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Asia/Taipei'
    }
  },
  SA: {
    name: 'Saudi Arabia',
    code: 'SA',
    region: 'Middle East',
    flag: '🇸🇦',
    currency: 'SAR',
    language: 'ar',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.15, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '12h',
    measurementSystem: 'metric',
    phoneFormat: '+966 XX XXX XXXX',
    addressFormat: {
      line1: 'رقم المبنى والشارع',
      line2: 'الحي',
      city: 'المدينة',
      state: 'المنطقة',
      postalCode: 'الرمز البريدي',
      postalCodePattern: '^\\d{5}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      pdplRequired: true,
      ageRestriction: 18,
      cookieConsent: 'required',
      dataResidency: 'SA',
      allowedPaymentMethods: ['card', 'stc_pay', 'apple_pay', 'mada'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Asia/Riyadh'
    }
  },
  TH: {
    name: 'Thailand',
    code: 'TH',
    region: 'Asia',
    flag: '🇹🇭',
    currency: 'THB',
    language: 'en',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.07, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+66 XX XXX XXXX',
    addressFormat: {
      line1: 'ที่อยู่',
      line2: 'ตำบล/แขวง',
      city: 'อำเภอ/เขต',
      state: 'จังหวัด',
      postalCode: 'รหัสไปรษณีย์',
      postalCodePattern: '^\\d{5}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      pdpaRequired: true,
      ageRestriction: 20,
      cookieConsent: 'required',
      dataResidency: 'TH',
      allowedPaymentMethods: ['card', 'promptpay', 'truemoney', 'rabbit_line_pay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Asia/Bangkok'
    }
  },
  VN: {
    name: 'Vietnam',
    code: 'VN',
    region: 'Asia',
    flag: '🇻🇳',
    currency: 'VND',
    language: 'vi',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.10, reduced: 0.05, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+84 XX XXXX XXXX',
    addressFormat: {
      line1: 'Số nhà, đường',
      line2: 'Phường/Xã',
      city: 'Quận/Huyện',
      state: 'Tỉnh/Thành phố',
      postalCode: 'Mã bưu điện',
      postalCodePattern: '^\\d{6}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      pdpRequired: true,
      ageRestriction: 16,
      cookieConsent: 'optional',
      dataResidency: 'VN',
      allowedPaymentMethods: ['card', 'momo', 'zalopay', 'vnpay', 'shopeepay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Asia/Ho_Chi_Minh'
    }
  },
  ZA: {
    name: 'South Africa',
    code: 'ZA',
    region: 'Africa',
    flag: '🇿🇦',
    currency: 'ZAR',
    language: 'en',
    alternativeLanguages: ['en', 'sw', 'sw'],
    taxSystem: 'vat',
    taxRates: { standard: 0.15, zero: 0 },
    taxInclusive: true,
    dateFormat: 'YYYY/MM/DD',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+27 XX XXX XXXX',
    addressFormat: {
      line1: 'Street Address',
      line2: 'Suburb',
      city: 'City',
      state: 'Province',
      postalCode: 'Postal Code',
      postalCodePattern: '^\\d{4}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      popiaRequired: true,
      ageRestriction: 18,
      cookieConsent: 'required',
      dataResidency: 'ZA',
      allowedPaymentMethods: ['card', 'paypal', 'snapscan', 'zapper', 'ozow'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Africa/Johannesburg'
    }
  },
  IT: {
    name: 'Italy',
    code: 'IT',
    region: 'Europe',
    flag: '🇮🇹',
    currency: 'EUR',
    language: 'it',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.22, reduced: 0.10, superReduced: 0.05, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+39 XXX XXX XXXX',
    addressFormat: {
      line1: 'Via e numero civico',
      line2: 'Interno (facoltativo)',
      city: 'Città',
      state: 'Provincia',
      postalCode: 'CAP',
      postalCodePattern: '^\\d{5}$'
    },
    compliance: {
      gdprRequired: true,
      ccpaRequired: false,
      ageRestriction: 14,
      cookieConsent: 'required',
      dataResidency: 'EU',
      allowedPaymentMethods: ['card', 'paypal', 'apple_pay', 'google_pay', 'satispay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Europe/Rome'
    }
  },
  NL: {
    name: 'Netherlands',
    code: 'NL',
    region: 'Europe',
    flag: '🇳🇱',
    currency: 'EUR',
    language: 'nl',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.21, reduced: 0.09, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD-MM-YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+31 X XXXX XXXX',
    addressFormat: {
      line1: 'Straat en huisnummer',
      line2: 'Toevoeging (optioneel)',
      city: 'Plaats',
      state: 'Provincie (optioneel)',
      postalCode: 'Postcode',
      postalCodePattern: '^\\d{4}\\s?[A-Z]{2}$'
    },
    compliance: {
      gdprRequired: true,
      ccpaRequired: false,
      ageRestriction: 16,
      cookieConsent: 'required',
      dataResidency: 'EU',
      allowedPaymentMethods: ['card', 'ideal', 'paypal', 'apple_pay', 'google_pay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Europe/Amsterdam'
    }
  },
  CH: {
    name: 'Switzerland',
    code: 'CH',
    region: 'Europe',
    flag: '🇨🇭',
    currency: 'CHF',
    language: 'de',
    alternativeLanguages: ['fr', 'en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.077, reduced: 0.025, low: 0.037, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD.MM.YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+41 XX XXX XX XX',
    addressFormat: {
      line1: 'Strasse und Hausnummer',
      line2: 'Zusatz (optional)',
      city: 'Ort',
      state: 'Kanton (optional)',
      postalCode: 'Postleitzahl',
      postalCodePattern: '^\\d{4}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      fadpRequired: true,
      ageRestriction: 13,
      cookieConsent: 'required',
      dataResidency: 'CH',
      allowedPaymentMethods: ['card', 'twint', 'paypal', 'apple_pay', 'google_pay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Europe/Zurich'
    }
  },
  PL: {
    name: 'Poland',
    code: 'PL',
    region: 'Europe',
    flag: '🇵🇱',
    currency: 'PLN',
    language: 'pl',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.23, reduced: 0.08, low: 0.05, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD.MM.YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+48 XXX XXX XXX',
    addressFormat: {
      line1: 'Ulica i numer',
      line2: 'Mieszkanie (opcjonalnie)',
      city: 'Miasto',
      state: 'Województwo',
      postalCode: 'Kod pocztowy',
      postalCodePattern: '^\\d{2}-\\d{3}$'
    },
    compliance: {
      gdprRequired: true,
      ccpaRequired: false,
      ageRestriction: 16,
      cookieConsent: 'required',
      dataResidency: 'EU',
      allowedPaymentMethods: ['card', 'blik', 'paypal', 'apple_pay', 'google_pay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Europe/Warsaw'
    }
  },
  SE: {
    name: 'Sweden',
    code: 'SE',
    region: 'Europe',
    flag: '🇸🇪',
    currency: 'SEK',
    language: 'sv',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.25, reduced: 0.12, low: 0.06, zero: 0 },
    taxInclusive: true,
    dateFormat: 'YYYY-MM-DD',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+46 XX XXX XX XX',
    addressFormat: {
      line1: 'Gatuadress',
      line2: 'Lägenhet (valfritt)',
      city: 'Ort',
      state: 'Län (valfritt)',
      postalCode: 'Postnummer',
      postalCodePattern: '^\\d{3}\\s?\\d{2}$'
    },
    compliance: {
      gdprRequired: true,
      ccpaRequired: false,
      ageRestriction: 13,
      cookieConsent: 'required',
      dataResidency: 'EU',
      allowedPaymentMethods: ['card', 'swish', 'paypal', 'apple_pay', 'google_pay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Europe/Stockholm'
    }
  },
  BE: {
    name: 'Belgium',
    code: 'BE',
    region: 'Europe',
    flag: '🇧🇪',
    currency: 'EUR',
    language: 'fr',
    alternativeLanguages: ['nl', 'de', 'en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.21, reduced: 0.06, intermediate: 0.12, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+32 XXX XX XX XX',
    addressFormat: {
      line1: 'Rue et numéro',
      line2: 'Boîte (optionnel)',
      city: 'Ville',
      state: 'Province (optionnel)',
      postalCode: 'Code postal',
      postalCodePattern: '^\\d{4}$'
    },
    compliance: {
      gdprRequired: true,
      ccpaRequired: false,
      ageRestriction: 13,
      cookieConsent: 'required',
      dataResidency: 'EU',
      allowedPaymentMethods: ['card', 'bancontact', 'paypal', 'apple_pay', 'google_pay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Europe/Brussels'
    }
  },
  AR: {
    name: 'Argentina',
    code: 'AR',
    region: 'South America',
    flag: '🇦🇷',
    currency: 'ARS',
    language: 'es',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.21, reduced: 0.105, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+54 XX XXXX XXXX',
    addressFormat: {
      line1: 'Calle y número',
      line2: 'Piso/Depto (opcional)',
      city: 'Ciudad',
      state: 'Provincia',
      postalCode: 'Código Postal',
      postalCodePattern: '^[A-Z]?\\d{4}[A-Z]{0,3}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      pdpRequired: true,
      ageRestriction: 18,
      cookieConsent: 'required',
      dataResidency: 'AR',
      allowedPaymentMethods: ['card', 'mercado_pago', 'paypal', 'rapipago', 'pagofacil'],
      shippingRestrictions: [],
      businessHoursTimezone: 'America/Argentina/Buenos_Aires'
    }
  },
  AT: {
    name: 'Austria',
    code: 'AT',
    region: 'Europe',
    flag: '🇦🇹',
    currency: 'EUR',
    language: 'de',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.20, reduced: 0.10, low: 0.13, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD.MM.YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+43 XXX XXXXXX',
    addressFormat: {
      line1: 'Straße und Hausnummer',
      line2: 'Stiege/Tür (optional)',
      city: 'Ort',
      state: 'Bundesland (optional)',
      postalCode: 'Postleitzahl',
      postalCodePattern: '^\\d{4}$'
    },
    compliance: {
      gdprRequired: true,
      ccpaRequired: false,
      ageRestriction: 14,
      cookieConsent: 'required',
      dataResidency: 'EU',
      allowedPaymentMethods: ['card', 'eps', 'paypal', 'apple_pay', 'google_pay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Europe/Vienna'
    }
  },
  NG: {
    name: 'Nigeria',
    code: 'NG',
    region: 'Africa',
    flag: '🇳🇬',
    currency: 'NGN',
    language: 'en',
    alternativeLanguages: [],
    taxSystem: 'vat',
    taxRates: { standard: 0.075, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '12h',
    measurementSystem: 'metric',
    phoneFormat: '+234 XXX XXX XXXX',
    addressFormat: {
      line1: 'Street Address',
      line2: 'Area',
      city: 'City',
      state: 'State',
      postalCode: 'Postal Code',
      postalCodePattern: '^\\d{6}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      ndprRequired: true,
      ageRestriction: 18,
      cookieConsent: 'optional',
      dataResidency: 'NG',
      allowedPaymentMethods: ['card', 'paystack', 'flutterwave', 'paypal'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Africa/Lagos'
    }
  },
  MY: {
    name: 'Malaysia',
    code: 'MY',
    region: 'Asia',
    flag: '🇲🇾',
    currency: 'MYR',
    language: 'en',
    alternativeLanguages: ['id', 'zh'],
    taxSystem: 'vat',
    taxRates: { standard: 0.06, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '12h',
    measurementSystem: 'metric',
    phoneFormat: '+60 XX XXXX XXXX',
    addressFormat: {
      line1: 'Street Address',
      line2: 'Taman/Area',
      city: 'City',
      state: 'State',
      postalCode: 'Postcode',
      postalCodePattern: '^\\d{5}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      pdpaRequired: true,
      ageRestriction: 18,
      cookieConsent: 'optional',
      dataResidency: 'MY',
      allowedPaymentMethods: ['card', 'fpx', 'grabpay', 'boost', 'tng'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Asia/Kuala_Lumpur'
    }
  },
  PH: {
    name: 'Philippines',
    code: 'PH',
    region: 'Asia',
    flag: '🇵🇭',
    currency: 'PHP',
    language: 'en',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.12, zero: 0 },
    taxInclusive: true,
    dateFormat: 'MM/DD/YYYY',
    timeFormat: '12h',
    measurementSystem: 'metric',
    phoneFormat: '+63 XXX XXX XXXX',
    addressFormat: {
      line1: 'Street Address',
      line2: 'Barangay',
      city: 'City',
      state: 'Province',
      postalCode: 'ZIP Code',
      postalCodePattern: '^\\d{4}$'
    },
    compliance: {
      gdprRequired: false,
      ccpaRequired: false,
      dpaRequired: true,
      ageRestriction: 18,
      cookieConsent: 'optional',
      dataResidency: 'PH',
      allowedPaymentMethods: ['card', 'gcash', 'paymaya', 'grabpay', 'shopeepay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Asia/Manila'
    }
  },
  DK: {
    name: 'Denmark',
    code: 'DK',
    region: 'Europe',
    flag: '🇩🇰',
    currency: 'DKK',
    language: 'da',
    alternativeLanguages: ['en'],
    taxSystem: 'vat',
    taxRates: { standard: 0.25, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD-MM-YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+45 XX XX XX XX',
    addressFormat: {
      line1: 'Vejnavn og nummer',
      line2: 'Etage/Side (valgfrit)',
      city: 'By',
      state: 'Region (valgfrit)',
      postalCode: 'Postnummer',
      postalCodePattern: '^\\d{4}$'
    },
    compliance: {
      gdprRequired: true,
      ccpaRequired: false,
      ageRestriction: 13,
      cookieConsent: 'required',
      dataResidency: 'EU',
      allowedPaymentMethods: ['card', 'mobilepay', 'paypal', 'apple_pay', 'google_pay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Europe/Copenhagen'
    }
  },
  FI: {
    name: 'Finland',
    code: 'FI',
    region: 'Europe',
    flag: '🇫🇮',
    currency: 'EUR',
    language: 'fi',
    alternativeLanguages: ['en', 'sv'],
    taxSystem: 'vat',
    taxRates: { standard: 0.24, reduced: 0.14, low: 0.10, zero: 0 },
    taxInclusive: true,
    dateFormat: 'DD.MM.YYYY',
    timeFormat: '24h',
    measurementSystem: 'metric',
    phoneFormat: '+358 XX XXX XXXX',
    addressFormat: {
      line1: 'Katuosoite',
      line2: 'Asunto (valinnainen)',
      city: 'Kaupunki',
      state: 'Maakunta (valinnainen)',
      postalCode: 'Postinumero',
      postalCodePattern: '^\\d{5}$'
    },
    compliance: {
      gdprRequired: true,
      ccpaRequired: false,
      ageRestriction: 13,
      cookieConsent: 'required',
      dataResidency: 'EU',
      allowedPaymentMethods: ['card', 'mobilepay', 'paypal', 'apple_pay', 'google_pay'],
      shippingRestrictions: [],
      businessHoursTimezone: 'Europe/Helsinki'
    }
  }
}

export const countryList = Object.values(countries).sort((a, b) => a.name.localeCompare(b.name))

export const regionGroups = {
  'North America': ['US', 'CA', 'MX'],
  'Europe': ['GB', 'DE', 'FR', 'NO', 'ES', 'RU', 'TR', 'IT', 'NL', 'CH', 'PL', 'SE', 'BE', 'AT', 'DK', 'FI'],
  'Asia': ['IN', 'JP', 'SG', 'KR', 'CN', 'ID', 'TW', 'TH', 'VN', 'MY', 'PH'],
  'Middle East': ['AE', 'SA'],
  'Oceania': ['AU'],
  'South America': ['BR', 'AR'],
  'Africa': ['ZA', 'NG']
}
