#!/bin/bash

# Batch Generation Script for All Missing Production Hub Tabs
# Total: 89 missing tabs

echo "🚀 Generating ALL missing production hub tabs..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# FILES MODULE (10 tabs) - PRIORITY 1
echo ""
echo "📁 FILES MODULE (10 tabs)..."
node scripts/generate-missing-tab-component.js files all-documents "All Documents"
node scripts/generate-missing-tab-component.js files contracts "Contracts"
node scripts/generate-missing-tab-component.js files riders "Riders"
node scripts/generate-missing-tab-component.js files tech-specs "Tech Specs"
node scripts/generate-missing-tab-component.js files call-sheets "Call Sheets"
node scripts/generate-missing-tab-component.js files insurance-permits "Insurance & Permits"
node scripts/generate-missing-tab-component.js files media-assets "Media Assets"
node scripts/generate-missing-tab-component.js files production-reports "Production Reports"
node scripts/generate-missing-tab-component.js files shared "Shared"
node scripts/generate-missing-tab-component.js files archive "Archive"

# FINANCE MODULE (11 tabs) - PRIORITY 1
echo ""
echo "💰 FINANCE MODULE (11 tabs)..."
node scripts/generate-missing-tab-component.js finance forecasts "Forecasts"
node scripts/generate-missing-tab-component.js finance budgets "Budgets"
node scripts/generate-missing-tab-component.js finance transactions "Transactions"
node scripts/generate-missing-tab-component.js finance revenue "Revenue"
node scripts/generate-missing-tab-component.js finance expenses "Expenses"
node scripts/generate-missing-tab-component.js finance payroll "Payroll"
node scripts/generate-missing-tab-component.js finance reconciliation "Reconciliation"
node scripts/generate-missing-tab-component.js finance payments "Payments"
node scripts/generate-missing-tab-component.js finance invoices "Invoices"
node scripts/generate-missing-tab-component.js finance taxes "Taxes"
node scripts/generate-missing-tab-component.js finance accounts "Accounts"
node scripts/generate-missing-tab-component.js finance gl-codes "GL Codes"

# PROCUREMENT MODULE (8 tabs) - PRIORITY 1
echo ""
echo "🛒 PROCUREMENT MODULE (8 tabs)..."
node scripts/generate-missing-tab-component.js procurement overview "Overview"
node scripts/generate-missing-tab-component.js procurement fulfillment "Fulfillment"
node scripts/generate-missing-tab-component.js procurement orders "Orders"
node scripts/generate-missing-tab-component.js procurement agreements "Agreements"
node scripts/generate-missing-tab-component.js procurement procurement-approvals "Approvals"
node scripts/generate-missing-tab-component.js procurement requisitions "Requisitions"
node scripts/generate-missing-tab-component.js procurement line-items "Line Items"
node scripts/generate-missing-tab-component.js procurement audits "Audits"

# JOBS MODULE (13 tabs) - PRIORITY 1
echo ""
echo "💼 JOBS MODULE (13 tabs)..."
node scripts/generate-missing-tab-component.js jobs overview "Overview"
node scripts/generate-missing-tab-component.js jobs active "Active"
node scripts/generate-missing-tab-component.js jobs offers "Offers"
node scripts/generate-missing-tab-component.js jobs shortlists "Shortlists"
node scripts/generate-missing-tab-component.js jobs rfps "RFPs"
node scripts/generate-missing-tab-component.js jobs completed "Completed"
node scripts/generate-missing-tab-component.js jobs archived "Archived"
node scripts/generate-missing-tab-component.js jobs work-orders "Work Orders"
node scripts/generate-missing-tab-component.js jobs dispatch "Dispatch"
node scripts/generate-missing-tab-component.js jobs estimates "Estimates"
node scripts/generate-missing-tab-component.js jobs jobs-compliance "Compliance"
node scripts/generate-missing-tab-component.js jobs checklists "Checklists"
node scripts/generate-missing-tab-component.js jobs recruiting "Recruiting"

# PROJECTS MODULE (9 tabs) - PRIORITY 2
echo ""
echo "📋 PROJECTS MODULE (9 tabs)..."
node scripts/generate-missing-tab-component.js projects overview "Overview"
node scripts/generate-missing-tab-component.js projects activations "Activations"
node scripts/generate-missing-tab-component.js projects tasks "Tasks"
node scripts/generate-missing-tab-component.js projects milestones "Milestones"
node scripts/generate-missing-tab-component.js projects compliance "Compliance"
node scripts/generate-missing-tab-component.js projects safety "Safety"
node scripts/generate-missing-tab-component.js projects projects-work-orders "Work Orders"
node scripts/generate-missing-tab-component.js projects costs "Costs"
node scripts/generate-missing-tab-component.js projects projects-checklists "Checklists"

# EVENTS MODULE (11 tabs) - PRIORITY 2
echo ""
echo "🎪 EVENTS MODULE (11 tabs)..."
node scripts/generate-missing-tab-component.js events all-events "All Events"
node scripts/generate-missing-tab-component.js events activities "Activities"
node scripts/generate-missing-tab-component.js events rehearsals "Rehearsals"
node scripts/generate-missing-tab-component.js events blocks "Blocks"
node scripts/generate-missing-tab-component.js events bookings "Bookings"
node scripts/generate-missing-tab-component.js events itineraries "Itineraries"
node scripts/generate-missing-tab-component.js events reservations "Reservations"
node scripts/generate-missing-tab-component.js events equipment "Equipment"
node scripts/generate-missing-tab-component.js events shipping-receiving "Shipping & Receiving"
node scripts/generate-missing-tab-component.js events trainings "Trainings"
node scripts/generate-missing-tab-component.js events incidents "Incidents"
node scripts/generate-missing-tab-component.js events internal "Internal"

# PEOPLE MODULE (8 tabs) - PRIORITY 2
echo ""
echo "👥 PEOPLE MODULE (8 tabs)..."
node scripts/generate-missing-tab-component.js people personnel "Personnel"
node scripts/generate-missing-tab-component.js people teams "Teams"
node scripts/generate-missing-tab-component.js people assignments "Assignments"
node scripts/generate-missing-tab-component.js people timekeeping "Timekeeping"
node scripts/generate-missing-tab-component.js people training "Training"
node scripts/generate-missing-tab-component.js people onboarding "Onboarding"
node scripts/generate-missing-tab-component.js people openings "Openings"
node scripts/generate-missing-tab-component.js people applicants "Applicants"

# COMPANIES MODULE (9 tabs) - PRIORITY 2
echo ""
echo "🏢 COMPANIES MODULE (9 tabs)..."
node scripts/generate-missing-tab-component.js companies deliverables "Deliverables"
node scripts/generate-missing-tab-component.js companies scopes-of-work "Scopes of Work"
node scripts/generate-missing-tab-component.js companies documents "Documents"
node scripts/generate-missing-tab-component.js companies bids "Bids"
node scripts/generate-missing-tab-component.js companies companies-compliance "Compliance"
node scripts/generate-missing-tab-component.js companies companies-work-orders "Work Orders"
node scripts/generate-missing-tab-component.js companies companies-invoices "Invoices"
node scripts/generate-missing-tab-component.js companies companies-reviews "Reviews"
node scripts/generate-missing-tab-component.js companies subcontractor-profile "Profile"

# LOCATIONS MODULE (7 tabs) - PRIORITY 3
echo ""
echo "📍 LOCATIONS MODULE (7 tabs)..."
node scripts/generate-missing-tab-component.js locations access "Access"
node scripts/generate-missing-tab-component.js locations warehousing "Warehousing"
node scripts/generate-missing-tab-component.js locations logistics "Logistics"
node scripts/generate-missing-tab-component.js locations utilities "Utilities"
node scripts/generate-missing-tab-component.js locations bim-models "BIM Models"
node scripts/generate-missing-tab-component.js locations coordination "Coordination"
node scripts/generate-missing-tab-component.js locations spatial-features "Spatial Features"

# ASSETS MODULE (3 tabs) - PRIORITY 3
echo ""
echo "📦 ASSETS MODULE (3 tabs)..."
node scripts/generate-missing-tab-component.js assets overview "Overview"
node scripts/generate-missing-tab-component.js assets tracking "Tracking"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ ALL 89 MISSING PRODUCTION HUB TABS GENERATED!"
echo ""
echo "Next steps:"
echo "1. Review generated components"
echo "2. Run: node scripts/audit-production-hub-only.js"
echo "3. Test functionality"
echo "4. Commit changes"
