// =============================================
// INSIGHTS MODULE - MOCK DATA
// Strategic insights, objectives, and AI-powered recommendations
// =============================================

export const mockObjectives = [
  {
    id: '1',
    title: 'Increase Revenue by 25%',
    description: 'Drive top-line growth through new client acquisition and expanded service offerings',
    category: 'Financial',
    status: 'on_track',
    priority: 'high',
    owner: 'Sarah Chen',
    ownerId: 'user-456',
    startDate: '2024-01-01',
    targetDate: '2024-12-31',
    progress: 68,
    confidence: 85,
    alignedTo: 'Company Growth Strategy',
    keyResults: ['kr-1', 'kr-2', 'kr-3'],
  },
  {
    id: '2',
    title: 'Expand into 3 New Markets',
    description: 'Establish presence in Austin, Nashville, and Miami by Q4',
    category: 'Growth',
    status: 'at_risk',
    priority: 'high',
    owner: 'Michael Torres',
    ownerId: 'user-789',
    startDate: '2024-03-01',
    targetDate: '2024-12-15',
    progress: 45,
    confidence: 65,
    alignedTo: 'Market Expansion Initiative',
    keyResults: ['kr-4', 'kr-5', 'kr-6'],
  },
  {
    id: '3',
    title: 'Improve Customer Satisfaction Score',
    description: 'Achieve and maintain NPS score above 70',
    category: 'Customer Success',
    status: 'on_track',
    priority: 'medium',
    owner: 'Jennifer Smith',
    ownerId: 'user-321',
    startDate: '2024-01-01',
    targetDate: '2024-12-31',
    progress: 82,
    confidence: 90,
    alignedTo: 'Customer Experience Strategy',
    keyResults: ['kr-7', 'kr-8'],
  },
  {
    id: '4',
    title: 'Reduce Operating Costs by 15%',
    description: 'Optimize operations and vendor relationships for cost efficiency',
    category: 'Operational Excellence',
    status: 'completed',
    priority: 'high',
    owner: 'David Lee',
    ownerId: 'user-654',
    startDate: '2024-01-01',
    targetDate: '2024-09-30',
    progress: 100,
    confidence: 100,
    alignedTo: 'Efficiency Initiative',
    keyResults: ['kr-9', 'kr-10'],
  },
  {
    id: '5',
    title: 'Launch New Service Line',
    description: 'Develop and launch virtual/hybrid event production services',
    category: 'Innovation',
    status: 'on_track',
    priority: 'medium',
    owner: 'Amanda White',
    ownerId: 'user-987',
    startDate: '2024-06-01',
    targetDate: '2025-03-31',
    progress: 35,
    confidence: 75,
    alignedTo: 'Product Innovation',
    keyResults: ['kr-11', 'kr-12', 'kr-13'],
  },
]

export const mockKeyResults = [
  {
    id: 'kr-1',
    objectiveId: '1',
    title: 'Acquire 50 new enterprise clients',
    target: 50,
    current: 34,
    unit: 'clients',
    progress: 68,
    status: 'on_track',
    dueDate: '2024-12-31',
  },
  {
    id: 'kr-2',
    objectiveId: '1',
    title: 'Increase average deal size to $250K',
    target: 250000,
    current: 215000,
    unit: 'USD',
    progress: 86,
    status: 'on_track',
    dueDate: '2024-12-31',
  },
  {
    id: 'kr-3',
    objectiveId: '1',
    title: 'Achieve 90% client retention rate',
    target: 90,
    current: 88,
    unit: 'percent',
    progress: 98,
    status: 'on_track',
    dueDate: '2024-12-31',
  },
  {
    id: 'kr-4',
    objectiveId: '2',
    title: 'Hire local teams in each market',
    target: 3,
    current: 1,
    unit: 'teams',
    progress: 33,
    status: 'at_risk',
    dueDate: '2024-10-31',
  },
  {
    id: 'kr-5',
    objectiveId: '2',
    title: 'Secure 5 anchor clients per market',
    target: 15,
    current: 8,
    unit: 'clients',
    progress: 53,
    status: 'at_risk',
    dueDate: '2024-12-15',
  },
  {
    id: 'kr-6',
    objectiveId: '2',
    title: 'Establish partnerships with 10 local vendors per market',
    target: 30,
    current: 12,
    unit: 'vendors',
    progress: 40,
    status: 'at_risk',
    dueDate: '2024-11-30',
  },
  {
    id: 'kr-7',
    objectiveId: '3',
    title: 'Achieve NPS score of 72+',
    target: 72,
    current: 71,
    unit: 'score',
    progress: 99,
    status: 'on_track',
    dueDate: '2024-12-31',
  },
  {
    id: 'kr-8',
    objectiveId: '3',
    title: 'Reduce average response time to 2 hours',
    target: 2,
    current: 2.1,
    unit: 'hours',
    progress: 95,
    status: 'on_track',
    dueDate: '2024-12-31',
  },
  {
    id: 'kr-9',
    objectiveId: '4',
    title: 'Reduce vendor costs by $500K annually',
    target: 500000,
    current: 550000,
    unit: 'USD',
    progress: 100,
    status: 'completed',
    dueDate: '2024-09-30',
  },
  {
    id: 'kr-10',
    objectiveId: '4',
    title: 'Automate 30% of manual processes',
    target: 30,
    current: 35,
    unit: 'percent',
    progress: 100,
    status: 'completed',
    dueDate: '2024-09-30',
  },
  {
    id: 'kr-11',
    objectiveId: '5',
    title: 'Complete product development',
    target: 100,
    current: 60,
    unit: 'percent',
    progress: 60,
    status: 'on_track',
    dueDate: '2024-12-31',
  },
  {
    id: 'kr-12',
    objectiveId: '5',
    title: 'Secure 5 beta clients',
    target: 5,
    current: 2,
    unit: 'clients',
    progress: 40,
    status: 'on_track',
    dueDate: '2025-01-31',
  },
  {
    id: 'kr-13',
    objectiveId: '5',
    title: 'Generate $500K in pre-launch pipeline',
    target: 500000,
    current: 150000,
    unit: 'USD',
    progress: 30,
    status: 'on_track',
    dueDate: '2025-03-31',
  },
]

export const mockBenchmarks = [
  {
    id: '1',
    category: 'Revenue Growth',
    metric: 'YoY Growth Rate',
    ourPerformance: 23,
    industryAverage: 15,
    topQuartile: 28,
    unit: 'percent',
    trend: 'up',
    comparison: 'above_average',
  },
  {
    id: '2',
    category: 'Operational Efficiency',
    metric: 'Labor Cost Ratio',
    ourPerformance: 42,
    industryAverage: 45,
    topQuartile: 38,
    unit: 'percent',
    trend: 'down',
    comparison: 'above_average',
  },
  {
    id: '3',
    category: 'Customer Satisfaction',
    metric: 'Net Promoter Score',
    ourPerformance: 71,
    industryAverage: 60,
    topQuartile: 75,
    unit: 'score',
    trend: 'up',
    comparison: 'above_average',
  },
  {
    id: '4',
    category: 'Financial Performance',
    metric: 'Gross Margin',
    ourPerformance: 35,
    industryAverage: 38,
    topQuartile: 45,
    unit: 'percent',
    trend: 'stable',
    comparison: 'below_average',
  },
  {
    id: '5',
    category: 'Team Performance',
    metric: 'Employee Retention Rate',
    ourPerformance: 87,
    industryAverage: 80,
    topQuartile: 92,
    unit: 'percent',
    trend: 'up',
    comparison: 'above_average',
  },
]

export const mockRecommendations = [
  {
    id: '1',
    title: 'Optimize Vendor Negotiations',
    description: 'Analysis shows potential for 12% cost reduction through consolidated vendor agreements',
    category: 'Cost Optimization',
    priority: 'high',
    impact: 'high',
    effort: 'medium',
    confidence: 87,
    source: 'ai_analysis',
    dataPoints: ['vendor_spending', 'contract_terms', 'market_rates'],
    estimatedSavings: 480000,
    estimatedTime: '3 months',
    status: 'new',
    createdAt: '2024-10-12',
  },
  {
    id: '2',
    title: 'Expand Marketing in Austin Market',
    description: 'Market analysis indicates 40% higher demand than current capacity in Austin region',
    category: 'Growth Opportunity',
    priority: 'high',
    impact: 'high',
    effort: 'high',
    confidence: 82,
    source: 'market_analysis',
    dataPoints: ['market_demand', 'competitor_gaps', 'revenue_potential'],
    estimatedRevenue: 1200000,
    estimatedTime: '6 months',
    status: 'in_review',
    createdAt: '2024-10-10',
  },
  {
    id: '3',
    title: 'Implement Predictive Maintenance',
    description: 'Equipment data suggests potential for 25% reduction in downtime through predictive maintenance',
    category: 'Operational Excellence',
    priority: 'medium',
    impact: 'medium',
    effort: 'low',
    confidence: 78,
    source: 'ai_analysis',
    dataPoints: ['equipment_failures', 'maintenance_logs', 'usage_patterns'],
    estimatedSavings: 180000,
    estimatedTime: '2 months',
    status: 'new',
    createdAt: '2024-10-08',
  },
  {
    id: '4',
    title: 'Enhance Client Onboarding Process',
    description: 'Client feedback analysis reveals opportunity to reduce time-to-value by 30%',
    category: 'Customer Success',
    priority: 'medium',
    impact: 'high',
    effort: 'low',
    confidence: 85,
    source: 'customer_feedback',
    dataPoints: ['onboarding_times', 'client_satisfaction', 'churn_analysis'],
    estimatedImpact: 'Improved retention by 8%',
    estimatedTime: '1 month',
    status: 'accepted',
    createdAt: '2024-10-05',
  },
]

export const mockPriorities = [
  {
    id: '1',
    title: 'Complete Market Expansion Hiring',
    description: 'Hire local teams in Austin and Nashville by November',
    dueDate: '2024-11-15',
    priority: 'critical',
    status: 'in_progress',
    progress: 60,
    owner: 'Michael Torres',
    linkedObjectives: ['2'],
  },
  {
    id: '2',
    title: 'Launch Q4 Marketing Campaign',
    description: 'Execute integrated campaign for new service line',
    dueDate: '2024-11-01',
    priority: 'high',
    status: 'in_progress',
    progress: 75,
    owner: 'Amanda White',
    linkedObjectives: ['5'],
  },
  {
    id: '3',
    title: 'Finalize Annual Budget',
    description: 'Complete 2025 budget planning and approval',
    dueDate: '2024-10-31',
    priority: 'high',
    status: 'in_progress',
    progress: 85,
    owner: 'David Lee',
    linkedObjectives: ['1', '4'],
  },
  {
    id: '4',
    title: 'Implement New CRM System',
    description: 'Complete CRM migration and team training',
    dueDate: '2024-12-15',
    priority: 'medium',
    status: 'not_started',
    progress: 0,
    owner: 'Sarah Chen',
    linkedObjectives: ['3'],
  },
]

export const mockProgressTracking = {
  overall: {
    objectivesTotal: 5,
    objectivesOnTrack: 3,
    objectivesAtRisk: 1,
    objectivesCompleted: 1,
    overallProgress: 66,
    trend: 'positive',
  },
  byCategory: [
    { category: 'Financial', progress: 84, status: 'on_track' },
    { category: 'Growth', progress: 45, status: 'at_risk' },
    { category: 'Customer Success', progress: 82, status: 'on_track' },
    { category: 'Operational Excellence', progress: 100, status: 'completed' },
    { category: 'Innovation', progress: 35, status: 'on_track' },
  ],
  timeline: [
    { month: 'Jan', progress: 15 },
    { month: 'Feb', progress: 22 },
    { month: 'Mar', progress: 28 },
    { month: 'Apr', progress: 35 },
    { month: 'May', progress: 42 },
    { month: 'Jun', progress: 48 },
    { month: 'Jul', progress: 54 },
    { month: 'Aug', progress: 60 },
    { month: 'Sep', progress: 66 },
    { month: 'Oct', progress: 66 },
  ],
}

export const mockReviews = [
  {
    id: '1',
    title: 'Q3 2024 Strategic Review',
    type: 'quarterly',
    date: '2024-09-30',
    status: 'completed',
    attendees: ['Sarah Chen', 'Michael Torres', 'David Lee', 'Jennifer Smith'],
    keyFindings: [
      'Revenue targets exceeded by 8%',
      'Market expansion behind schedule',
      'Customer satisfaction at all-time high',
    ],
    actionItems: [
      'Accelerate Austin market hiring',
      'Reallocate resources from completed objectives',
      'Continue current customer success initiatives',
    ],
    nextReview: '2024-12-31',
  },
  {
    id: '2',
    title: 'Mid-Year 2024 Review',
    type: 'semi-annual',
    date: '2024-06-30',
    status: 'completed',
    attendees: ['Leadership Team'],
    keyFindings: [
      'On track for annual revenue goals',
      'Cost reduction ahead of schedule',
      'New service line development progressing well',
    ],
    actionItems: [
      'Maintain current trajectory',
      'Begin Q3 expansion planning',
      'Prepare for beta launch',
    ],
    nextReview: '2024-09-30',
  },
]

export const mockIntelligenceFeed = [
  {
    id: '1',
    type: 'insight',
    title: 'Revenue Velocity Increasing',
    description: 'Sales cycle shortened by 18% over past 3 months',
    category: 'Performance',
    source: 'sales_data',
    timestamp: '2024-10-14T10:30:00Z',
    priority: 'medium',
    actionable: true,
  },
  {
    id: '2',
    type: 'alert',
    title: 'Austin Market Hiring Behind Schedule',
    description: 'Only 1 of 3 target hires completed with 6 weeks remaining',
    category: 'Risk',
    source: 'objective_tracking',
    timestamp: '2024-10-14T09:15:00Z',
    priority: 'high',
    actionable: true,
  },
  {
    id: '3',
    type: 'opportunity',
    title: 'Competitor Gap Identified in Miami',
    description: 'Market analysis shows underserved corporate event segment',
    category: 'Growth',
    source: 'market_intelligence',
    timestamp: '2024-10-13T14:20:00Z',
    priority: 'medium',
    actionable: true,
  },
  {
    id: '4',
    type: 'insight',
    title: 'Equipment Utilization Optimized',
    description: 'Asset sharing program increased utilization to 87%',
    category: 'Efficiency',
    source: 'asset_data',
    timestamp: '2024-10-13T11:00:00Z',
    priority: 'low',
    actionable: false,
  },
]

export const mockSuccessMetrics = [
  {
    id: '1',
    name: 'Revenue per Employee',
    value: 285000,
    target: 250000,
    unit: 'USD',
    trend: 'up',
    change: 14,
    status: 'exceeding',
  },
  {
    id: '2',
    name: 'Customer Lifetime Value',
    value: 450000,
    target: 400000,
    unit: 'USD',
    trend: 'up',
    change: 12.5,
    status: 'exceeding',
  },
  {
    id: '3',
    name: 'Project Success Rate',
    value: 96,
    target: 95,
    unit: 'percent',
    trend: 'stable',
    change: 0,
    status: 'on_target',
  },
  {
    id: '4',
    name: 'Average Project Margin',
    value: 32,
    target: 35,
    unit: 'percent',
    trend: 'down',
    change: -2,
    status: 'below_target',
  },
  {
    id: '5',
    name: 'Team Productivity Index',
    value: 118,
    target: 110,
    unit: 'index',
    trend: 'up',
    change: 7.3,
    status: 'exceeding',
  },
]

// Helper function to simulate async data loading
export const simulateDelay = (ms: number = 500) => {
  return new Promise(resolve => setTimeout(resolve, ms))
}
