import type { ModuleTab, ViewType } from '@/types'

const ALL_VIEWS: ViewType[] = [
  'list', 'board', 'table', 'calendar', 'timeline', 'workload', 'map',
  'mind-map', 'form', 'activity', 'box', 'embed', 'chat', 'dashboard',
  'doc', 'financial', 'portfolio', 'pivot',
]

// Helper to create tabs
const createTab = (
  id: string,
  module_id: string,
  name: string,
  slug: string,
  icon: string,
  order: number,
  defaultView: ViewType = 'list',
  description?: string,
  color?: string
): ModuleTab => ({
  id,
  module_id,
  name,
  slug,
  description,
  icon,
  order,
  enabled: true,
  default_view: defaultView,
  available_views: ALL_VIEWS,
  color,
})

export const MODULE_TABS: Record<string, ModuleTab[]> = {
  dashboard: [
    createTab('dashboard-overview', 'dashboard', 'Overview', 'overview', 'LayoutDashboard', 0, 'dashboard', 'A customizable widget based dashboard', '#8b5cf6'),
    createTab('dashboard-my-agenda', 'dashboard', 'My Agenda', 'my-agenda', 'Calendar', 1, 'calendar', 'Events including you or created by you', '#dc2626'),
    createTab('dashboard-my-jobs', 'dashboard', 'My Jobs', 'my-jobs', 'Briefcase', 2, 'list', 'Your contracts and scopes of work', '#2563eb'),
    createTab('dashboard-my-tasks', 'dashboard', 'My Tasks', 'my-tasks', 'CheckSquare', 3, 'list', 'Your assigned and created tasks', '#7c3aed'),
    createTab('dashboard-my-assets', 'dashboard', 'My Assets', 'my-assets', 'Package', 4, 'table', 'Personal inventories of owned and rented equipment', '#ea580c'),
    createTab('dashboard-my-orders', 'dashboard', 'My Orders', 'my-orders', 'ShoppingCart', 5, 'list', 'Orders to be integrated with marketplace', '#059669'),
    createTab('dashboard-my-advances', 'dashboard', 'My Advances', 'my-advances', 'TrendingUp', 6, 'list', 'Equipment, credentials, materials, and asset requests', '#f59e0b'),
    createTab('dashboard-my-travel', 'dashboard', 'My Travel', 'my-travel', 'Plane', 7, 'calendar', 'Your travel arrangements and itineraries', '#0891b2'),
    createTab('dashboard-my-expenses', 'dashboard', 'My Expenses', 'my-expenses', 'Receipt', 8, 'table', 'Your expense reports and submissions', '#16a34a'),
    createTab('dashboard-my-reports', 'dashboard', 'My Reports', 'my-reports', 'FileBarChart', 9, 'table', 'Custom, favorited and recurring reports', '#8b5cf6'),
    createTab('dashboard-my-files', 'dashboard', 'My Files', 'my-files', 'FolderOpen', 10, 'table', 'Files uploaded, downloaded, saved, favorited', '#7c3aed'),
  ],
  projects: [
    createTab('projects-overview', 'projects', 'Overview', 'overview', 'LayoutDashboard', 0, 'dashboard', 'Project overview & key metrics', '#8b5cf6'),
    createTab('projects-productions', 'projects', 'Productions', 'productions', 'Clapperboard', 1, 'table', 'All projects including shows, tours, and events', '#7c3aed'),
    createTab('projects-activations', 'projects', 'Activations', 'activations', 'Sparkles', 2, 'table', 'Stages, art installations, brand activations, guest amenities', '#f59e0b'),
    createTab('projects-schedule', 'projects', 'Schedule', 'schedule', 'Calendar', 3, 'timeline', 'Production and build schedule', '#2563eb'),
    createTab('projects-tasks', 'projects', 'Tasks', 'tasks', 'CheckSquare', 4, 'list', 'Project tasks and assignments', '#16a34a'),
    createTab('projects-milestones', 'projects', 'Milestones', 'milestones', 'Flag', 5, 'timeline', 'Key project milestones and deadlines', '#dc2626'),
    createTab('projects-compliance', 'projects', 'Compliance', 'compliance', 'ShieldCheck', 6, 'table', 'Licensing, permitting, inspections, and regulatory compliance', '#ea580c'),
    createTab('projects-safety', 'projects', 'Safety', 'safety', 'ShieldAlert', 7, 'table', 'Risk assessments, safety guidelines, emergency procedures', '#dc2626'),
  ],
  events: [
    createTab('events-all-events', 'events', 'All Events', 'all-events', 'Calendar', 0, 'calendar', 'All scheduled events and activities', '#8b5cf6'),
    createTab('events-activities', 'events', 'Activities', 'activities', 'Sparkles', 1, 'table', 'Performances, rehearsals, classes, workshops, recreation', '#7c3aed'),
    createTab('events-run-of-show', 'events', 'Run of Show', 'run-of-show', 'ListOrdered', 2, 'timeline', 'Detailed show rundowns and cue sheets', '#dc2626'),
    createTab('events-rehearsals', 'events', 'Rehearsals', 'rehearsals', 'Repeat', 3, 'calendar', 'Rehearsal schedules and sessions', '#2563eb'),
    createTab('events-blocks', 'events', 'Blocks', 'blocks', 'LayoutGrid', 4, 'table', 'Room blocks, dressing rooms, green rooms, studio blocks', '#f59e0b'),
    createTab('events-bookings', 'events', 'Bookings', 'bookings', 'MapPin', 5, 'calendar', 'Venue bookings and reservations', '#16a34a'),
    createTab('events-tours', 'events', 'Tours', 'tours', 'Route', 6, 'timeline', 'Tour dates and multi-city schedules', '#0891b2'),
    createTab('events-itineraries', 'events', 'Itineraries', 'itineraries', 'Plane', 7, 'list', 'Travel itineraries and schedules', '#ea580c'),
    createTab('events-reservations', 'events', 'Reservations', 'reservations', 'Utensils', 8, 'table', 'Hospitality and entertainment reservations', '#059669'),
    createTab('events-equipment', 'events', 'Equipment', 'equipment', 'Package', 9, 'table', 'Event equipment assignments and tracking', '#64748b'),
    createTab('events-shipping-receiving', 'events', 'Shipping & Receiving', 'shipping-receiving', 'Truck', 10, 'list', 'Shipments and deliveries for events', '#f59e0b'),
    createTab('events-trainings', 'events', 'Trainings', 'trainings', 'GraduationCap', 11, 'calendar', 'Training sessions and workshops', '#7c3aed'),
    createTab('events-incidents', 'events', 'Incidents', 'incidents', 'AlertTriangle', 12, 'table', 'Incident reports and safety issues', '#dc2626'),
    createTab('events-internal', 'events', 'Internal', 'internal', 'Building2', 13, 'list', 'Administrative and internal events', '#64748b'),
  ],
  people: [
    createTab('people-personnel', 'people', 'Personnel', 'personnel', 'Users', 0, 'table', 'All personnel, crew, and staff members', '#2563eb'),
    createTab('people-teams', 'people', 'Teams', 'teams', 'UsersRound', 1, 'table', 'Teams, departments, and working groups', '#7c3aed'),
    createTab('people-assignments', 'people', 'Assignments', 'assignments', 'ClipboardCheck', 2, 'table', 'Project tasks and timeline assignments', '#8b5cf6'),
    createTab('people-timekeeping', 'people', 'Timekeeping', 'timekeeping', 'Clock', 3, 'table', 'Time tracking and attendance records', '#059669'),
    createTab('people-scheduling', 'people', 'Scheduling', 'scheduling', 'Calendar', 4, 'calendar', 'Crew scheduling and availability', '#ea580c'),
    createTab('people-training', 'people', 'Training', 'training', 'GraduationCap', 5, 'list', 'Training programs and certifications', '#f59e0b'),
    createTab('people-onboarding', 'people', 'Onboarding', 'onboarding', 'UserPlus', 6, 'list', 'New hire onboarding process', '#16a34a'),
    createTab('people-openings', 'people', 'Openings', 'openings', 'Briefcase', 7, 'table', 'Open positions and job postings', '#0891b2'),
    createTab('people-applicants', 'people', 'Applicants', 'applicants', 'UserRoundSearch', 8, 'table', 'Job applicants and candidates', '#dc2626'),
  ],
  assets: [
    createTab('assets-overview', 'assets', 'Overview', 'overview', 'LayoutDashboard', 0, 'dashboard', 'Asset management overview & metrics', '#ea580c'),
    createTab('assets-tracking', 'assets', 'Tracking', 'tracking', 'ScanLine', 1, 'table', 'Asset lifespan, check-in/out, location tracking', '#2563eb'),
    createTab('assets-inventory', 'assets', 'Inventory', 'inventory', 'Package', 2, 'table', 'Current asset inventory and stock levels', '#7c3aed'),
    createTab('assets-maintenance', 'assets', 'Maintenance', 'maintenance', 'Wrench', 3, 'calendar', 'Maintenance schedules, service, and repairs', '#dc2626'),
    createTab('assets-approvals', 'assets', 'Approvals', 'approvals', 'ClipboardCheck', 4, 'table', 'Approval workflows for production advances', '#16a34a'),
    createTab('assets-advances', 'assets', 'Advances', 'advances', 'TrendingUp', 5, 'table', 'Production advances for equipment and materials', '#f59e0b'),
    createTab('assets-catalog', 'assets', 'Catalog', 'catalog', 'BookOpen', 6, 'table', 'Complete asset catalog: infrastructure, equipment, vehicles, tools, credentials', '#8b5cf6'),
  ],
  locations: [
    createTab('locations-directory', 'locations', 'Directory', 'directory', 'Building2', 0, 'table', 'Venues, offices, warehouses, rooms, and facilities', '#2563eb'),
    createTab('locations-site-maps', 'locations', 'Site Maps', 'site-maps', 'Map', 1, 'map', 'Facility layouts and floor plans', '#16a34a'),
    createTab('locations-access', 'locations', 'Access', 'access', 'DoorOpen', 2, 'table', 'Access points, security, and entry management', '#ea580c'),
    createTab('locations-warehousing', 'locations', 'Warehousing', 'warehousing', 'Warehouse', 3, 'table', 'Storage facilities and inventory locations', '#64748b'),
    createTab('locations-logistics', 'locations', 'Logistics', 'logistics', 'Truck', 4, 'timeline', 'Transportation, shipping, and delivery coordination', '#0891b2'),
    createTab('locations-utilities', 'locations', 'Utilities', 'utilities', 'Zap', 5, 'table', 'Power, water, internet, and infrastructure', '#f59e0b'),
  ],
  files: [
    createTab('files-all-documents', 'files', 'All Documents', 'all-documents', 'FileText', 0, 'table', 'All production documents', '#4f46e5'),
    createTab('files-contracts', 'files', 'Contracts', 'contracts', 'FileSignature', 1, 'table', 'Vendor & talent contracts', '#059669'),
    createTab('files-riders', 'files', 'Riders', 'riders', 'ScrollText', 2, 'table', 'Technical & hospitality riders', '#7c3aed'),
    createTab('files-tech-specs', 'files', 'Tech Specs', 'tech-specs', 'FileCode', 3, 'table', 'Technical specifications & drawings', '#2563eb'),
    createTab('files-call-sheets', 'files', 'Call Sheets', 'call-sheets', 'ClipboardList', 4, 'list', 'Daily call sheets & schedules', '#ea580c'),
    createTab('files-insurance-permits', 'files', 'Insurance & Permits', 'insurance-permits', 'ShieldCheck', 5, 'table', 'Insurance certs & permits', '#16a34a'),
    createTab('files-media-assets', 'files', 'Media Assets', 'media-assets', 'Image', 6, 'box', 'Photos, videos, graphics', '#8b5cf6'),
    createTab('files-production-reports', 'files', 'Production Reports', 'production-reports', 'FileBarChart', 7, 'table', 'Daily reports & documentation', '#0891b2'),
    createTab('files-shared', 'files', 'Shared', 'shared', 'Share2', 8, 'table', 'Shared with external parties', '#f59e0b'),
    createTab('files-archive', 'files', 'Archive', 'archive', 'FolderClosed', 9, 'table', 'Archived production files', '#64748b'),
  ],
  admin: [
    createTab('admin-overview', 'admin', 'Overview', 'overview', 'Gauge', 0, 'dashboard', 'Organization overview & metrics', '#64748b'),
    createTab('admin-organization', 'admin', 'Organization', 'organization', 'Building2', 1, 'table', 'Organization settings & profile', '#2563eb'),
    createTab('admin-invite', 'admin', 'Invite', 'invite', 'UserSquare2', 2, 'table', 'Invite team members', '#7c3aed'),
    createTab('admin-roles-permissions', 'admin', 'Roles & Permissions', 'roles-permissions', 'Shield', 3, 'table', 'Access control & permissions', '#8b5cf6'),
    createTab('admin-billing', 'admin', 'Billing', 'billing', 'CreditCard', 4, 'table', 'Subscription & billing', '#059669'),
    createTab('admin-security', 'admin', 'Security', 'security', 'Lock', 5, 'table', 'Security settings & logs', '#dc2626'),
    createTab('admin-templates', 'admin', 'Templates', 'templates', 'FileText', 6, 'table', 'Organization templates & resources', '#7c3aed'),
    createTab('admin-automations', 'admin', 'Automations', 'automations', 'Bot', 7, 'table', 'Workflow automation rules', '#8b5cf6'),
    createTab('admin-integrations', 'admin', 'Integrations', 'integrations', 'Zap', 8, 'table', 'Third-party integrations', '#f59e0b'),
    createTab('admin-webhooks', 'admin', 'Webhooks', 'webhooks', 'Webhook', 9, 'table', 'Webhook configurations', '#06b6d4'),
    createTab('admin-api-tokens', 'admin', 'API Tokens', 'api-tokens', 'Key', 10, 'table', 'API access tokens', '#64748b'),
  ],
  settings: [
    createTab('settings-appearance', 'settings', 'Appearance', 'appearance', 'Palette', 0, 'form', 'Customize your interface with themes and custom styles', '#8b5cf6'),
    createTab('settings-integrations', 'settings', 'Integrations', 'integrations', 'Plug', 1, 'table', 'Connect personal and organization integrations', '#f59e0b'),
    createTab('settings-automations', 'settings', 'Automations', 'automations', 'Bot', 2, 'table', 'Personal workflow automations', '#8b5cf6'),
    createTab('settings-account', 'settings', 'Account', 'account', 'UserCircle', 3, 'form', 'Account information and security settings', '#3b82f6'),
    createTab('settings-team', 'settings', 'Team', 'team', 'Users', 4, 'table', 'Team member management', '#7c3aed'),
    createTab('settings-billing', 'settings', 'Billing', 'billing', 'CreditCard', 5, 'table', 'Subscription and billing management', '#059669'),
  ],
  profile: [
    createTab('profile-basic-info', 'profile', 'Basic', 'basic-info', 'User', 0, 'form', 'Personal details and contact information', '#3b82f6'),
    createTab('profile-professional', 'profile', 'Professional', 'professional', 'Briefcase', 1, 'form', 'Resume, work experience, and education', '#2563eb'),
    createTab('profile-social', 'profile', 'Social', 'social', 'Share2', 2, 'form', 'Social media profiles and links', '#8b5cf6'),
    createTab('profile-certifications', 'profile', 'Certifications', 'certifications', 'Award', 3, 'table', 'Professional licenses and credentials', '#16a34a'),
    createTab('profile-travel', 'profile', 'Travel', 'travel', 'Plane', 4, 'form', 'Passport, TSA PreCheck, and travel preferences', '#0891b2'),
    createTab('profile-health', 'profile', 'Health', 'health', 'Heart', 5, 'form', 'Medical information and dietary restrictions', '#dc2626'),
    createTab('profile-emergency', 'profile', 'Emergency', 'emergency', 'AlertCircle', 6, 'form', 'Emergency contacts and information', '#ea580c'),
    createTab('profile-performance', 'profile', 'Performance', 'performance', 'TrendingUp', 7, 'dashboard', 'Performance metrics and ratings', '#10b981'),
    createTab('profile-endorsements', 'profile', 'Endorsements', 'endorsements', 'ThumbsUp', 8, 'list', 'Skill endorsements and recommendations', '#f59e0b'),
    createTab('profile-tags', 'profile', 'Tags', 'tags', 'Tags', 9, 'table', 'System tags for matching opportunities', '#7c3aed'),
    createTab('profile-history', 'profile', 'History', 'history', 'Clock', 10, 'table', 'Complete project history', '#64748b'),
  ],
  companies: [
    createTab('companies-organizations', 'companies', 'Organizations', 'organizations', 'Building2', 0, 'table', 'All companies and organizations', '#2563eb'),
    createTab('companies-contacts', 'companies', 'Contacts', 'contacts', 'UserCircle', 1, 'table', 'Roles and responsibilities attached to companies', '#7c3aed'),
    createTab('companies-deliverables', 'companies', 'Deliverables', 'deliverables', 'PackageCheck', 2, 'table', 'Company deliverables and milestones', '#16a34a'),
    createTab('companies-scopes-of-work', 'companies', 'Scopes of Work', 'scopes-of-work', 'ClipboardList', 3, 'table', 'Project scopes and work specifications', '#8b5cf6'),
    createTab('companies-documents', 'companies', 'Documents', 'documents', 'FileText', 4, 'table', 'COIs, certifications, proposals, and company documents', '#f59e0b'),
    createTab('companies-bids', 'companies', 'Bids', 'bids', 'DollarSign', 5, 'table', 'Company bids and quotes', '#059669'),
  ],
  community: [
    createTab('community-news', 'community', 'News', 'news', 'Newspaper', 0, 'activity', 'Industry news, sponsored and curated content', '#2563eb'),
    createTab('community-showcase', 'community', 'Showcase', 'showcase', 'Sparkles', 1, 'activity', 'Featured posts and sponsored content feed', '#8b5cf6'),
    createTab('community-activity', 'community', 'Activity', 'activity', 'MessageCircle', 2, 'activity', 'Social activity feed with 500 character limit', '#7c3aed'),
    createTab('community-connections', 'community', 'Connections', 'connections', 'Users', 3, 'table', 'Professional connections and network', '#10b981'),
    createTab('community-studios', 'community', 'Studios', 'studios', 'Building2', 4, 'table', 'Professional pages and groups community', '#f59e0b'),
    createTab('community-events', 'community', 'Events', 'events', 'CalendarDays', 5, 'calendar', 'Curated public productions and events', '#dc2626'),
    createTab('community-discussions', 'community', 'Discussions', 'discussions', 'MessageSquare', 6, 'list', 'Reddit-style threaded discussions', '#0891b2'),
    createTab('community-competitions', 'community', 'Competitions', 'competitions', 'Trophy', 7, 'table', 'Competitions with leaderboards and rankings', '#ea580c'),
  ],
  marketplace: [
    createTab('marketplace-spotlight', 'marketplace', 'Spotlight', 'spotlight', 'Sparkles', 0, 'activity', 'Instagram-style feed: sponsored, curated, and featured products', '#8b5cf6'),
    createTab('marketplace-shop', 'marketplace', 'Shop', 'shop', 'ShoppingCart', 1, 'box', 'Shopify-style e-commerce browsing', '#2563eb'),
    createTab('marketplace-favorites', 'marketplace', 'Favorites', 'favorites', 'Heart', 2, 'box', 'Saved & favorited items', '#dc2626'),
    createTab('marketplace-sales', 'marketplace', 'Sales', 'sales', 'TrendingUp', 3, 'table', 'Your sales as a vendor/supplier', '#059669'),
    createTab('marketplace-purchases', 'marketplace', 'Purchases', 'purchases', 'ClipboardList', 4, 'table', 'Your marketplace purchases and orders', '#ea580c'),
    createTab('marketplace-lists', 'marketplace', 'Lists', 'lists', 'ListChecks', 5, 'list', 'Saved lists, shopping carts, and wishlists', '#7c3aed'),
    createTab('marketplace-products', 'marketplace', 'Products', 'products', 'Package', 6, 'box', 'Browse all marketplace products', '#0891b2'),
    createTab('marketplace-services', 'marketplace', 'Services', 'services', 'Handshake', 7, 'table', 'Professional services & support', '#16a34a'),
    createTab('marketplace-vendors', 'marketplace', 'Vendors', 'vendors', 'Store', 8, 'table', 'Marketplace vendors & sellers', '#6366f1'),
    createTab('marketplace-reviews', 'marketplace', 'Reviews', 'reviews', 'Star', 9, 'list', 'Ratings & reviews', '#f59e0b'),
  ],
  resources: [
    createTab('resources-library', 'resources', 'Library', 'library', 'BookOpen', 0, 'table', 'All Resources', '#0891b2'),
    createTab('resources-guides', 'resources', 'Guides', 'guides', 'Book', 1, 'list', 'How-to guides & tutorials', '#2563eb'),
    createTab('resources-courses', 'resources', 'Courses', 'courses', 'GraduationCap', 2, 'table', 'Educational courses & programs', '#7c3aed'),
    createTab('resources-trainings', 'resources', 'Trainings', 'trainings', 'UserRoundCog', 3, 'calendar', 'Training sessions & workshops', '#dc2626'),
    createTab('resources-grants', 'resources', 'Grants', 'grants', 'CircleDollarSign', 4, 'table', 'Funding opportunities & grant applications', '#16a34a'),
    createTab('resources-publications', 'resources', 'Publications', 'publications', 'FileText', 5, 'table', 'Industry publications & research', '#8b5cf6'),
    createTab('resources-glossary', 'resources', 'Glossary', 'glossary', 'BookMarked', 6, 'table', 'Industry terms & definitions', '#ea580c'),
    createTab('resources-troubleshooting', 'resources', 'Troubleshooting', 'troubleshooting', 'Wrench', 7, 'list', 'Common issues & solutions', '#64748b'),
  ],
  finance: [
    createTab('finance-overview', 'finance', 'Overview', 'overview', 'LayoutDashboard', 0, 'dashboard', 'Financial overview & metrics', '#059669'),
    createTab('finance-forecasting', 'finance', 'Forecasting', 'forecasting', 'TrendingUpDown', 1, 'dashboard', 'Budget forecasting & projections using line item rate ranges', '#0891b2'),
    createTab('finance-budgets', 'finance', 'Budgets', 'budgets', 'Wallet', 2, 'financial', 'Production budgets & forecasts', '#2563eb'),
    createTab('finance-transactions', 'finance', 'Transactions', 'transactions', 'ArrowLeftRight', 3, 'table', 'All financial transactions & entries', '#7c3aed'),
    createTab('finance-revenue', 'finance', 'Revenue', 'revenue', 'TrendingUp', 4, 'financial', 'Revenue streams & income tracking', '#16a34a'),
    createTab('finance-expenses', 'finance', 'Expenses', 'expenses', 'Receipt', 5, 'table', 'Expense tracking & reimbursements', '#ea580c'),
    createTab('finance-payroll', 'finance', 'Payroll', 'payroll', 'WalletCards', 6, 'table', 'Crew payroll management', '#2563eb'),
    createTab('finance-reconciliation', 'finance', 'Reconciliation', 'reconciliation', 'CircleCheckBig', 7, 'table', 'Project & show settlements', '#8b5cf6'),
    createTab('finance-payments', 'finance', 'Payments', 'payments', 'CreditCard', 8, 'table', 'Payment processing & history', '#10b981'),
    createTab('finance-invoices', 'finance', 'Invoices', 'invoices', 'ScrollText', 9, 'table', 'Invoicing & billing', '#f59e0b'),
    createTab('finance-taxes', 'finance', 'Taxes', 'taxes', 'Calculator', 10, 'table', 'Tax documents & compliance', '#dc2626'),
    createTab('finance-accounts', 'finance', 'Accounts', 'accounts', 'Landmark', 11, 'table', 'Accounting categories & classifications', '#64748b'),
    createTab('finance-gl-codes', 'finance', 'GL Codes', 'gl-codes', 'Hash', 12, 'table', 'General ledger code management', '#6366f1'),
  ],
  procurement: [
    createTab('procurement-overview', 'procurement', 'Overview', 'overview', 'ChartSpline', 0, 'dashboard', 'Procurement overview & metrics', '#d97706'),
    createTab('procurement-fulfillment', 'procurement', 'Fulfillment', 'fulfillment', 'PackageCheck', 1, 'table', 'Order fulfillment tracking & status', '#16a34a'),
    createTab('procurement-orders', 'procurement', 'Orders', 'orders', 'ShoppingCart', 2, 'table', 'Work orders, purchase orders, change orders, talent orders', '#2563eb'),
    createTab('procurement-agreements', 'procurement', 'Agreements', 'agreements', 'FileSignature', 3, 'table', 'Service agreements, vendor contracts, and procurement agreements', '#0891b2'),
    createTab('procurement-approvals', 'procurement', 'Approvals', 'approvals', 'ClipboardCheck', 4, 'table', 'Approval workflows & pending reviews', '#f59e0b'),
    createTab('procurement-requisitions', 'procurement', 'Requisitions', 'requisitions', 'ClipboardList', 5, 'list', 'Purchase requisitions & requests', '#64748b'),
    createTab('procurement-line-items', 'procurement', 'Line Items', 'line-items', 'List', 6, 'table', 'Line items with approved rate ranges for forecasting', '#7c3aed'),
    createTab('procurement-audits', 'procurement', 'Audits', 'audits', 'FileSearch', 7, 'table', 'Procurement audits, compliance & review history', '#8b5cf6'),
  ],
  jobs: [
    createTab('jobs-overview', 'jobs', 'Overview', 'overview', 'ChartNoAxesCombined', 0, 'dashboard', 'Jobs overview & metrics', '#8b5cf6'),
    createTab('jobs-active', 'jobs', 'Active', 'active', 'Briefcase', 1, 'table', 'Active contracts and jobs', '#16a34a'),
    createTab('jobs-pipeline', 'jobs', 'Pipeline', 'pipeline', 'GitGraph', 2, 'board', 'Jobs in negotiation and proposal stages', '#2563eb'),
    createTab('jobs-offers', 'jobs', 'Offers', 'offers', 'FileHeart', 3, 'table', 'Job offers awaiting acceptance or counter-offers', '#059669'),
    createTab('jobs-shortlists', 'jobs', 'Shortlists', 'shortlists', 'ListChecks', 4, 'table', 'Shortlisted opportunities and bids', '#7c3aed'),
    createTab('jobs-rfps', 'jobs', 'RFPs', 'rfps', 'ScrollText', 5, 'table', 'Requests for proposals and bidding opportunities', '#ea580c'),
    createTab('jobs-completed', 'jobs', 'Completed', 'completed', 'CircleCheckBig', 6, 'table', 'Successfully completed jobs', '#10b981'),
    createTab('jobs-archived', 'jobs', 'Archived', 'archived', 'FolderMinus', 7, 'table', 'Canceled, terminated, or fully reconciled jobs', '#64748b'),
  ],
  reports: [
    createTab('reports-overview', 'reports', 'Overview', 'overview', 'ChartColumnBig', 0, 'dashboard', 'Recent reports and activity dashboard', '#0284c7'),
    createTab('reports-custom-builder', 'reports', 'Custom Builder', 'custom-builder', 'Wrench', 1, 'form', 'Build custom reports with drag-and-drop interface', '#2563eb'),
    createTab('reports-templates', 'reports', 'Templates', 'templates', 'FileStack', 2, 'table', 'Pre-built report templates library', '#7c3aed'),
    createTab('reports-scheduled', 'reports', 'Scheduled', 'scheduled', 'Calendar', 3, 'calendar', 'Automated report generation and delivery', '#dc2626'),
    createTab('reports-exports', 'reports', 'Exports', 'exports', 'Download', 4, 'table', 'Export history and download center', '#0891b2'),
    createTab('reports-compliance', 'reports', 'Compliance', 'compliance', 'ShieldCheck', 5, 'table', 'Regulatory and compliance reports', '#16a34a'),
    createTab('reports-executive', 'reports', 'Executive', 'executive', 'Crown', 6, 'table', 'C-suite and stakeholder reports', '#8b5cf6'),
    createTab('reports-operational', 'reports', 'Operational', 'operational', 'Activity', 7, 'table', 'Day-to-day operational reports', '#f59e0b'),
    createTab('reports-archived', 'reports', 'Archived', 'archived', 'Archive', 8, 'table', 'Historical report storage', '#64748b'),
  ],
  analytics: [
    createTab('analytics-overview', 'analytics', 'Overview', 'overview', 'ChartCandlestick', 0, 'dashboard', 'Analytics dashboard with key metrics', '#7c3aed'),
    createTab('analytics-performance', 'analytics', 'Performance', 'performance', 'Gauge', 1, 'dashboard', 'Performance metrics and benchmarking', '#16a34a'),
    createTab('analytics-trends', 'analytics', 'Trends', 'trends', 'LineChart', 2, 'dashboard', 'Historical trends and pattern analysis', '#0891b2'),
    createTab('analytics-comparisons', 'analytics', 'Comparisons', 'comparisons', 'BarChart2', 3, 'pivot', 'Comparative analysis across datasets', '#8b5cf6'),
    createTab('analytics-forecasting', 'analytics', 'Forecasting', 'forecasting', 'TrendingUpDown', 4, 'dashboard', 'Predictive analytics and projections', '#f59e0b'),
    createTab('analytics-realtime', 'analytics', 'Real-time', 'realtime', 'Waves', 5, 'activity', 'Live metrics and monitoring', '#dc2626'),
    createTab('analytics-custom-views', 'analytics', 'Custom Views', 'custom-views', 'Sliders', 6, 'pivot', 'Build custom analytics dashboards', '#7c3aed'),
    createTab('analytics-pivot-tables', 'analytics', 'Pivot Tables', 'pivot-tables', 'Table', 7, 'pivot', 'Advanced data exploration', '#2563eb'),
    createTab('analytics-metrics-library', 'analytics', 'Metrics Library', 'metrics-library', 'BookMarked', 8, 'table', 'Saved metrics and KPIs', '#059669'),
    createTab('analytics-data-sources', 'analytics', 'Data Sources', 'data-sources', 'Database', 9, 'table', 'Manage connected data sources', '#64748b'),
  ],
  insights: [
    createTab('insights-overview', 'insights', 'Overview', 'overview', 'Lightbulb', 0, 'dashboard', 'Strategic insights dashboard', '#10b981'),
    createTab('insights-objectives', 'insights', 'Objectives', 'objectives', 'Target', 1, 'table', 'Strategic objectives and initiatives', '#2563eb'),
    createTab('insights-key-results', 'insights', 'Key Results', 'key-results', 'CheckCircle2', 2, 'table', 'Measurable outcomes and milestones', '#16a34a'),
    createTab('insights-benchmarks', 'insights', 'Benchmarks', 'benchmarks', 'BarChart3', 3, 'dashboard', 'Industry benchmarks and best practices', '#0891b2'),
    createTab('insights-recommendations', 'insights', 'Recommendations', 'recommendations', 'Sparkles', 4, 'activity', 'AI-powered strategic recommendations', '#8b5cf6'),
    createTab('insights-priorities', 'insights', 'Priorities', 'priorities', 'ListOrdered', 5, 'table', 'Ranked priorities and focus areas', '#f59e0b'),
    createTab('insights-progress-tracking', 'insights', 'Progress Tracking', 'progress-tracking', 'TrendingUp', 6, 'dashboard', 'Track progress against strategic goals', '#059669'),
    createTab('insights-reviews', 'insights', 'Reviews', 'reviews', 'ClipboardCheck', 7, 'calendar', 'Periodic reviews and retrospectives', '#7c3aed'),
    createTab('insights-intelligence-feed', 'insights', 'Intelligence Feed', 'intelligence-feed', 'Rss', 8, 'activity', 'Curated insights from all data sources', '#dc2626'),
    createTab('insights-success-metrics', 'insights', 'Success Metrics', 'success-metrics', 'Award', 9, 'dashboard', 'Define and track success criteria', '#ea580c'),
  ],
}

export function getModuleTabs(moduleId: string): ModuleTab[] {
  return MODULE_TABS[moduleId] || []
}

export function getTabBySlug(moduleId: string, tabSlug: string): ModuleTab | undefined {
  const tabs = MODULE_TABS[moduleId] || []
  return tabs.find((tab) => tab.slug === tabSlug)
}
