import type { ModuleTab, ViewType } from '@/types'

const ALL_VIEWS: ViewType[] = [
  'list', 'board', 'table', 'calendar', 'timeline', 'workload', 'map',
  'mind-map', 'form', 'activity', 'box', 'embed', 'chat', 'dashboard',
  'doc', 'financial', 'portfolio', 'pivot',
]

// Helper to create tabs
const createTab = (
  id: string,
  module_id: string,
  name: string,
  slug: string,
  icon: string,
  order: number,
  defaultView: ViewType = 'list',
  description?: string,
  color?: string
): ModuleTab => ({
  id,
  module_id,
  name,
  slug,
  description,
  icon,
  order,
  enabled: true,
  default_view: defaultView,
  available_views: ALL_VIEWS,
  color,
})

export const MODULE_TABS: Record<string, ModuleTab[]> = {
  dashboard: [
    createTab('dashboard-overview', 'dashboard', 'Overview', 'overview', 'LayoutDashboard', 0, 'dashboard', 'Production overview & key metrics', '#8b5cf6'),
    createTab('dashboard-active-productions', 'dashboard', 'Active Productions', 'active-productions', 'Clapperboard', 1, 'board', 'Live and in-progress productions', '#16a34a'),
    createTab('dashboard-crew-workload', 'dashboard', 'Crew Workload', 'crew-workload', 'Users', 2, 'workload', 'Team capacity & assignments', '#2563eb'),
    createTab('dashboard-show-schedule', 'dashboard', 'Show Schedule', 'show-schedule', 'Calendar', 3, 'calendar', 'Upcoming shows & performances', '#dc2626'),
    createTab('dashboard-my-assignments', 'dashboard', 'My Assignments', 'my-assignments', 'UserCheck', 4, 'list', 'Personal task & role assignments', '#7c3aed'),
    createTab('dashboard-production-pipeline', 'dashboard', 'Production Pipeline', 'production-pipeline', 'GitBranch', 5, 'timeline', 'Production lifecycle stages', '#ea580c'),
    createTab('dashboard-budget-overview', 'dashboard', 'Budget Overview', 'budget-overview', 'DollarSign', 6, 'financial', 'Financial performance across productions', '#059669'),
    createTab('dashboard-vendor-status', 'dashboard', 'Vendor Status', 'vendor-status', 'Truck', 7, 'table', 'Vendor deliverables & timelines', '#0891b2'),
    createTab('dashboard-activity-feed', 'dashboard', 'Activity Feed', 'activity-feed', 'Activity', 8, 'activity', 'Recent production updates', '#8b5cf6'),
    createTab('dashboard-analytics', 'dashboard', 'Analytics', 'analytics', 'TrendingUp', 9, 'dashboard', 'Production performance analytics', '#7c3aed'),
  ],
  projects: [
    createTab('projects-all-productions', 'projects', 'All Productions', 'all-productions', 'Clapperboard', 0, 'board', 'All production projects', '#7c3aed'),
    createTab('projects-pre-production', 'projects', 'Pre-Production', 'pre-production', 'FileEdit', 1, 'board', 'Planning & design phase', '#f59e0b'),
    createTab('projects-in-production', 'projects', 'In Production', 'in-production', 'Play', 2, 'board', 'Active build & rehearsal', '#16a34a'),
    createTab('projects-load-in', 'projects', 'Load-In', 'load-in', 'TruckIcon', 3, 'timeline', 'Installation & setup phase', '#2563eb'),
    createTab('projects-live-run', 'projects', 'Live Run', 'live-run', 'Radio', 4, 'calendar', 'Active show dates', '#dc2626'),
    createTab('projects-strike-load-out', 'projects', 'Strike/Load-Out', 'strike-load-out', 'PackageOpen', 5, 'timeline', 'Teardown & removal', '#ea580c'),
    createTab('projects-post-production', 'projects', 'Post-Production', 'post-production', 'FileCheck', 6, 'list', 'Wrap & reconciliation', '#7c3aed'),
    createTab('projects-budget-tracking', 'projects', 'Budget Tracking', 'budget-tracking', 'DollarSign', 7, 'financial', 'Production budgets & actuals', '#059669'),
    createTab('projects-crew-assignments', 'projects', 'Crew Assignments', 'crew-assignments', 'Users', 8, 'workload', 'Crew scheduling & roles', '#8b5cf6'),
    createTab('projects-archive', 'projects', 'Archive', 'archive', 'Archive', 9, 'table', 'Completed productions', '#64748b'),
  ],
  events: [
    createTab('events-show-calendar', 'events', 'Show Calendar', 'show-calendar', 'Calendar', 0, 'calendar', 'All show dates & performances', '#dc2626'),
    createTab('events-upcoming-shows', 'events', 'Upcoming Shows', 'upcoming-shows', 'PlayCircle', 1, 'list', 'Next performances & events', '#16a34a'),
    createTab('events-tour-dates', 'events', 'Tour Dates', 'tour-dates', 'Route', 2, 'timeline', 'Multi-city tour schedules', '#2563eb'),
    createTab('events-call-times', 'events', 'Call Times', 'call-times', 'Clock', 3, 'table', 'Crew & talent call schedules', '#ea580c'),
    createTab('events-rehearsals', 'events', 'Rehearsals', 'rehearsals', 'Repeat', 4, 'calendar', 'Rehearsal schedules', '#7c3aed'),
    createTab('events-production-meetings', 'events', 'Production Meetings', 'production-meetings', 'Users', 5, 'list', 'Meetings & reviews', '#0891b2'),
    createTab('events-deadlines', 'events', 'Deadlines', 'deadlines', 'AlertCircle', 6, 'list', 'Critical production deadlines', '#dc2626'),
    createTab('events-venue-availability', 'events', 'Venue Availability', 'venue-availability', 'MapPin', 7, 'calendar', 'Venue booking & access', '#8b5cf6'),
    createTab('events-tech-schedules', 'events', 'Tech Schedules', 'tech-schedules', 'Wrench', 8, 'timeline', 'Technical rehearsals & cue-to-cue', '#f59e0b'),
    createTab('events-past-shows', 'events', 'Past Shows', 'past-shows', 'Archive', 9, 'table', 'Completed performances', '#64748b'),
  ],
  people: [
    createTab('people-crew-roster', 'people', 'Crew Roster', 'crew-roster', 'Users', 0, 'table', 'All crew members & staff', '#2563eb'),
    createTab('people-talent-artists', 'people', 'Talent & Artists', 'talent-artists', 'Mic', 1, 'table', 'Performers, artists, speakers', '#8b5cf6'),
    createTab('people-vendors', 'people', 'Vendors', 'vendors', 'Store', 2, 'table', 'Suppliers & service providers', '#059669'),
    createTab('people-contractors', 'people', 'Contractors', 'contractors', 'Briefcase', 3, 'table', 'Freelance & contract workers', '#7c3aed'),
    createTab('people-departments', 'people', 'Departments', 'departments', 'Layers', 4, 'mind-map', 'Production departments', '#ea580c'),
    createTab('people-availability', 'people', 'Availability', 'availability', 'Calendar', 5, 'calendar', 'Crew & talent availability', '#dc2626'),
    createTab('people-certifications', 'people', 'Certifications', 'certifications', 'Award', 6, 'table', 'Licenses & certifications', '#f59e0b'),
    createTab('people-payroll', 'people', 'Payroll', 'payroll', 'DollarSign', 7, 'table', 'Rates & payment tracking', '#059669'),
    createTab('people-contacts', 'people', 'Contacts', 'contacts', 'Phone', 8, 'table', 'Emergency & primary contacts', '#0891b2'),
    createTab('people-onboarding', 'people', 'Onboarding', 'onboarding', 'UserPlus', 9, 'list', 'New crew onboarding', '#16a34a'),
  ],
  assets: [
    createTab('assets-inventory', 'assets', 'Inventory', 'inventory', 'Package', 0, 'table', 'Full equipment inventory', '#ea580c'),
    createTab('assets-audio', 'assets', 'Audio', 'audio', 'Music', 1, 'table', 'Sound systems & audio gear', '#7c3aed'),
    createTab('assets-lighting', 'assets', 'Lighting', 'lighting', 'Lightbulb', 2, 'table', 'Lighting fixtures & control', '#f59e0b'),
    createTab('assets-video', 'assets', 'Video', 'video', 'Video', 3, 'table', 'Video & projection equipment', '#2563eb'),
    createTab('assets-staging-rigging', 'assets', 'Staging & Rigging', 'staging-rigging', 'Box', 4, 'table', 'Stages, truss, rigging gear', '#64748b'),
    createTab('assets-rentals', 'assets', 'Rentals', 'rentals', 'ShoppingCart', 5, 'table', 'Rented equipment tracking', '#059669'),
    createTab('assets-check-out-in', 'assets', 'Check-Out/In', 'check-out-in', 'ArrowRightLeft', 6, 'list', 'Equipment assignments', '#8b5cf6'),
    createTab('assets-maintenance', 'assets', 'Maintenance', 'maintenance', 'Wrench', 7, 'calendar', 'Service & repair schedules', '#dc2626'),
    createTab('assets-transportation', 'assets', 'Transportation', 'transportation', 'Truck', 8, 'list', 'Vehicles & trucking', '#0891b2'),
    createTab('assets-depreciation', 'assets', 'Depreciation', 'depreciation', 'TrendingDown', 9, 'financial', 'Asset value tracking', '#dc2626'),
  ],
  locations: [
    createTab('locations-venue-map', 'locations', 'Venue Map', 'venue-map', 'Map', 0, 'map', 'Geographic venue locations', '#16a34a'),
    createTab('locations-venues', 'locations', 'Venues', 'venues', 'Building', 1, 'table', 'Performance venues & facilities', '#2563eb'),
    createTab('locations-stages', 'locations', 'Stages', 'stages', 'Box', 2, 'table', 'Stage configurations & specs', '#7c3aed'),
    createTab('locations-load-in-access', 'locations', 'Load-In Access', 'load-in-access', 'TruckIcon', 3, 'table', 'Loading docks & access points', '#ea580c'),
    createTab('locations-backstage-areas', 'locations', 'Backstage Areas', 'backstage-areas', 'DoorClosed', 4, 'table', 'Dressing rooms, green rooms, storage', '#0891b2'),
    createTab('locations-warehouse-storage', 'locations', 'Warehouse & Storage', 'warehouse-storage', 'Warehouse', 5, 'table', 'Equipment storage facilities', '#64748b'),
    createTab('locations-site-surveys', 'locations', 'Site Surveys', 'site-surveys', 'FileCheck', 6, 'list', 'Venue assessments & tech specs', '#8b5cf6'),
    createTab('locations-power-utilities', 'locations', 'Power & Utilities', 'power-utilities', 'Zap', 7, 'table', 'Power distribution & utilities', '#f59e0b'),
    createTab('locations-permits-access', 'locations', 'Permits & Access', 'permits-access', 'ShieldCheck', 8, 'table', 'Venue permits & access credentials', '#059669'),
    createTab('locations-tour-routing', 'locations', 'Tour Routing', 'tour-routing', 'Route', 9, 'map', 'Multi-city tour logistics', '#dc2626'),
  ],
  files: [
    createTab('files-all-documents', 'files', 'All Documents', 'all-documents', 'FileText', 0, 'table', 'All production documents', '#4f46e5'),
    createTab('files-contracts', 'files', 'Contracts', 'contracts', 'FileSignature', 1, 'table', 'Vendor & talent contracts', '#059669'),
    createTab('files-riders', 'files', 'Riders', 'riders', 'ScrollText', 2, 'table', 'Technical & hospitality riders', '#7c3aed'),
    createTab('files-tech-specs', 'files', 'Tech Specs', 'tech-specs', 'FileCode', 3, 'table', 'Technical specifications & drawings', '#2563eb'),
    createTab('files-call-sheets', 'files', 'Call Sheets', 'call-sheets', 'ClipboardList', 4, 'list', 'Daily call sheets & schedules', '#ea580c'),
    createTab('files-insurance-permits', 'files', 'Insurance & Permits', 'insurance-permits', 'ShieldCheck', 5, 'table', 'Insurance certs & permits', '#16a34a'),
    createTab('files-media-assets', 'files', 'Media Assets', 'media-assets', 'Image', 6, 'box', 'Photos, videos, graphics', '#8b5cf6'),
    createTab('files-production-reports', 'files', 'Production Reports', 'production-reports', 'FileBarChart', 7, 'table', 'Daily reports & documentation', '#0891b2'),
    createTab('files-shared', 'files', 'Shared', 'shared', 'Share2', 8, 'table', 'Shared with external parties', '#f59e0b'),
    createTab('files-archive', 'files', 'Archive', 'archive', 'Archive', 9, 'table', 'Archived production files', '#64748b'),
  ],
  admin: [
    createTab('admin-overview', 'admin', 'Overview', 'overview', 'LayoutDashboard', 0, 'dashboard', 'Organization overview & metrics', '#64748b'),
    createTab('admin-organization', 'admin', 'Organization', 'organization', 'Building', 1, 'table', 'Organization settings & profile', '#2563eb'),
    createTab('admin-members', 'admin', 'Members', 'members', 'Users', 2, 'table', 'Team member management', '#7c3aed'),
    createTab('admin-roles-permissions', 'admin', 'Roles & Permissions', 'roles-permissions', 'Shield', 3, 'table', 'Access control & permissions', '#8b5cf6'),
    createTab('admin-billing', 'admin', 'Billing', 'billing', 'CreditCard', 4, 'table', 'Subscription & billing', '#059669'),
    createTab('admin-security', 'admin', 'Security', 'security', 'Lock', 5, 'table', 'Security settings & logs', '#dc2626'),
    createTab('admin-automations', 'admin', 'Automations', 'automations', 'Bot', 6, 'table', 'Workflow automation rules', '#8b5cf6'),
    createTab('admin-integrations', 'admin', 'Integrations', 'integrations', 'Zap', 7, 'table', 'Third-party integrations', '#f59e0b'),
    createTab('admin-webhooks', 'admin', 'Webhooks', 'webhooks', 'Webhook', 8, 'table', 'Webhook configurations', '#06b6d4'),
    createTab('admin-api-tokens', 'admin', 'API Tokens', 'api-tokens', 'Key', 9, 'table', 'API access tokens', '#64748b'),
  ],
  companies: [
    createTab('companies-all-companies', 'companies', 'All Companies', 'all-companies', 'Building2', 0, 'table', 'Complete company directory', '#2563eb'),
    createTab('companies-clients', 'companies', 'Clients', 'clients', 'BadgeCheck', 1, 'table', 'Client organizations & relationships', '#16a34a'),
    createTab('companies-vendors', 'companies', 'Vendors', 'vendors', 'Store', 2, 'table', 'Vendor & supplier companies', '#059669'),
    createTab('companies-partners', 'companies', 'Partners', 'partners', 'Users2', 3, 'table', 'Strategic partner organizations', '#7c3aed'),
    createTab('companies-sponsors', 'companies', 'Sponsors', 'sponsors', 'Award', 4, 'table', 'Sponsoring companies & brands', '#f59e0b'),
    createTab('companies-agencies', 'companies', 'Agencies', 'agencies', 'Briefcase', 5, 'table', 'Talent, production, & creative agencies', '#8b5cf6'),
    createTab('companies-contacts', 'companies', 'Contacts', 'contacts', 'UserCircle', 6, 'table', 'Key company contacts & decision makers', '#2563eb'),
    createTab('companies-contracts', 'companies', 'Contracts', 'contracts', 'FileSignature', 7, 'table', 'Company contracts & agreements', '#0891b2'),
    createTab('companies-invoicing', 'companies', 'Invoicing', 'invoicing', 'Receipt', 8, 'financial', 'Company invoices & payments', '#059669'),
    createTab('companies-performance', 'companies', 'Performance', 'performance', 'TrendingUp', 9, 'dashboard', 'Company ratings & performance metrics', '#dc2626'),
  ],
  community: [
    createTab('community-my-network', 'community', 'My Network', 'my-network', 'Network', 0, 'table', 'Your professional connections & network overview', '#10b981'),
    createTab('community-directory', 'community', 'Directory', 'directory', 'UserCircle2', 1, 'table', 'Complete community member directory', '#2563eb'),
    createTab('community-connections', 'community', 'Connections', 'connections', 'Users2', 2, 'table', 'Direct connections & relationships', '#7c3aed'),
    createTab('community-messages', 'community', 'Messages', 'messages', 'MessageSquare', 3, 'chat', 'Community conversations & communications', '#0891b2'),
    createTab('community-activity', 'community', 'Activity', 'activity', 'Activity', 4, 'activity', 'Community activity feed & updates', '#8b5cf6'),
    createTab('community-recommendations', 'community', 'Recommendations', 'recommendations', 'ThumbsUp', 5, 'list', 'Member endorsements & recommendations', '#f59e0b'),
    createTab('community-groups', 'community', 'Groups', 'groups', 'Users', 6, 'table', 'Professional groups & communities', '#16a34a'),
    createTab('community-events', 'community', 'Events', 'events', 'CalendarDays', 7, 'calendar', 'Community networking events & meetups', '#dc2626'),
    createTab('community-notes', 'community', 'Notes', 'notes', 'FileText', 8, 'list', 'Member notes & interaction history', '#64748b'),
    createTab('community-insights', 'community', 'Insights', 'insights', 'LineChart', 9, 'dashboard', 'Community analytics & growth metrics', '#059669'),
  ],
  marketplace: [
    createTab('marketplace-browse', 'marketplace', 'Browse', 'browse', 'Store', 0, 'box', 'Browse all marketplace items', '#7c3aed'),
    createTab('marketplace-templates', 'marketplace', 'Templates', 'templates', 'LayoutTemplate', 1, 'box', 'Production templates & workflows', '#2563eb'),
    createTab('marketplace-integrations', 'marketplace', 'Integrations', 'integrations', 'Puzzle', 2, 'table', 'Third-party integrations & plugins', '#0891b2'),
    createTab('marketplace-services', 'marketplace', 'Services', 'services', 'Users', 3, 'table', 'Professional services & support', '#16a34a'),
    createTab('marketplace-equipment', 'marketplace', 'Equipment', 'equipment', 'Package', 4, 'box', 'Rental equipment listings', '#ea580c'),
    createTab('marketplace-freelancers', 'marketplace', 'Freelancers', 'freelancers', 'UserCircle', 5, 'table', 'Available crew & contractors', '#8b5cf6'),
    createTab('marketplace-my-purchases', 'marketplace', 'My Purchases', 'my-purchases', 'ShoppingBag', 6, 'list', 'Your purchase history', '#059669'),
    createTab('marketplace-favorites', 'marketplace', 'Favorites', 'favorites', 'Heart', 7, 'box', 'Saved & favorited items', '#dc2626'),
    createTab('marketplace-vendors', 'marketplace', 'Vendors', 'vendors', 'Building2', 8, 'table', 'Marketplace vendors & sellers', '#7c3aed'),
    createTab('marketplace-reviews', 'marketplace', 'Reviews', 'reviews', 'Star', 9, 'list', 'Ratings & reviews', '#f59e0b'),
  ],
  resources: [
    createTab('resources-all-resources', 'resources', 'All Resources', 'all-resources', 'BookOpen', 0, 'table', 'Complete resource library', '#0891b2'),
    createTab('resources-guides', 'resources', 'Guides', 'guides', 'Book', 1, 'list', 'How-to guides & tutorials', '#2563eb'),
    createTab('resources-templates', 'resources', 'Templates', 'templates', 'FileText', 2, 'box', 'Document & workflow templates', '#7c3aed'),
    createTab('resources-videos', 'resources', 'Videos', 'videos', 'Video', 3, 'box', 'Video tutorials & training', '#dc2626'),
    createTab('resources-best-practices', 'resources', 'Best Practices', 'best-practices', 'Award', 4, 'list', 'Industry best practices & standards', '#16a34a'),
    createTab('resources-case-studies', 'resources', 'Case Studies', 'case-studies', 'FileCheck', 5, 'list', 'Real-world production examples', '#8b5cf6'),
    createTab('resources-downloads', 'resources', 'Downloads', 'downloads', 'Download', 6, 'table', 'Downloadable assets & files', '#ea580c'),
    createTab('resources-community', 'resources', 'Community', 'community', 'Users', 7, 'activity', 'Community discussions & knowledge sharing', '#0891b2'),
    createTab('resources-faq', 'resources', 'FAQ', 'faq', 'HelpCircle', 8, 'list', 'Frequently asked questions', '#64748b'),
    createTab('resources-glossary', 'resources', 'Glossary', 'glossary', 'BookMarked', 9, 'table', 'Industry terms & definitions', '#7c3aed'),
  ],
  finance: [
    createTab('finance-overview', 'finance', 'Overview', 'overview', 'LayoutDashboard', 0, 'dashboard', 'Financial overview & metrics', '#059669'),
    createTab('finance-budgets', 'finance', 'Budgets', 'budgets', 'Wallet', 1, 'financial', 'Production budgets & forecasts', '#2563eb'),
    createTab('finance-expenses', 'finance', 'Expenses', 'expenses', 'Receipt', 2, 'table', 'Expense tracking & reimbursements', '#ea580c'),
    createTab('finance-invoices', 'finance', 'Invoices', 'invoices', 'FileText', 3, 'table', 'Invoicing & billing', '#7c3aed'),
    createTab('finance-payments', 'finance', 'Payments', 'payments', 'CreditCard', 4, 'table', 'Payment processing & history', '#16a34a'),
    createTab('finance-payroll', 'finance', 'Payroll', 'payroll', 'Users', 5, 'table', 'Crew payroll management', '#0891b2'),
    createTab('finance-accounts', 'finance', 'Accounts', 'accounts', 'Landmark', 6, 'table', 'Chart of accounts & categories', '#64748b'),
    createTab('finance-reconciliation', 'finance', 'Reconciliation', 'reconciliation', 'CheckCircle2', 7, 'table', 'Bank reconciliation & matching', '#16a34a'),
    createTab('finance-reports', 'finance', 'Reports', 'reports', 'FileBarChart', 8, 'dashboard', 'Financial reports & statements', '#8b5cf6'),
    createTab('finance-tax', 'finance', 'Tax', 'tax', 'Calculator', 9, 'table', 'Tax documents & compliance', '#dc2626'),
  ],
  procurement: [
    createTab('procurement-overview', 'procurement', 'Overview', 'overview', 'LayoutDashboard', 0, 'dashboard', 'Procurement overview & metrics', '#d97706'),
    createTab('procurement-purchase-orders', 'procurement', 'Purchase Orders', 'purchase-orders', 'ShoppingCart', 1, 'table', 'All purchase orders', '#2563eb'),
    createTab('procurement-pending', 'procurement', 'Pending', 'pending', 'Clock', 2, 'table', 'Pending approvals & reviews', '#f59e0b'),
    createTab('procurement-approved', 'procurement', 'Approved', 'approved', 'CheckCircle2', 3, 'table', 'Approved purchase orders', '#16a34a'),
    createTab('procurement-received', 'procurement', 'Received', 'received', 'PackageCheck', 4, 'table', 'Received shipments & deliveries', '#0891b2'),
    createTab('procurement-vendors', 'procurement', 'Vendors', 'vendors', 'Store', 5, 'table', 'Vendor directory & contacts', '#7c3aed'),
    createTab('procurement-contracts', 'procurement', 'Contracts', 'contracts', 'FileSignature', 6, 'table', 'Vendor contracts & agreements', '#8b5cf6'),
    createTab('procurement-inventory', 'procurement', 'Inventory', 'inventory', 'Package', 7, 'table', 'Stock levels & reorder points', '#ea580c'),
    createTab('procurement-spending', 'procurement', 'Spending', 'spending', 'TrendingUp', 8, 'financial', 'Spending analysis & trends', '#059669'),
    createTab('procurement-requisitions', 'procurement', 'Requisitions', 'requisitions', 'ClipboardList', 9, 'list', 'Purchase requisitions', '#64748b'),
  ],
  jobs: [
    createTab('jobs-overview', 'jobs', 'Overview', 'overview', 'LayoutDashboard', 0, 'dashboard', 'Hiring overview & metrics', '#8b5cf6'),
    createTab('jobs-all-jobs', 'jobs', 'All Jobs', 'all-jobs', 'Briefcase', 1, 'table', 'All job postings', '#2563eb'),
    createTab('jobs-active-postings', 'jobs', 'Active Postings', 'active-postings', 'Megaphone', 2, 'board', 'Currently active job posts', '#16a34a'),
    createTab('jobs-applicants', 'jobs', 'Applicants', 'applicants', 'Users', 3, 'table', 'Job applicants & candidates', '#7c3aed'),
    createTab('jobs-interviews', 'jobs', 'Interviews', 'interviews', 'Video', 4, 'calendar', 'Interview schedules', '#ea580c'),
    createTab('jobs-offers', 'jobs', 'Offers', 'offers', 'FileCheck', 5, 'table', 'Job offers & negotiations', '#059669'),
    createTab('jobs-onboarding', 'jobs', 'Onboarding', 'onboarding', 'UserPlus', 6, 'list', 'New hire onboarding', '#0891b2'),
    createTab('jobs-departments', 'jobs', 'Departments', 'departments', 'Building', 7, 'table', 'Department hiring needs', '#64748b'),
    createTab('jobs-pipeline', 'jobs', 'Pipeline', 'pipeline', 'GitBranch', 8, 'board', 'Hiring pipeline stages', '#8b5cf6'),
    createTab('jobs-archive', 'jobs', 'Archive', 'archive', 'Archive', 9, 'table', 'Closed job postings', '#64748b'),
  ],
  reports: [
    createTab('reports-overview', 'reports', 'Overview', 'overview', 'LayoutDashboard', 0, 'dashboard', 'Reports overview & recent reports', '#0284c7'),
    createTab('reports-custom-builder', 'reports', 'Custom Builder', 'custom-builder', 'Wrench', 1, 'form', 'Build custom reports', '#2563eb'),
    createTab('reports-templates', 'reports', 'Templates', 'templates', 'LayoutTemplate', 2, 'table', 'Report templates library', '#7c3aed'),
    createTab('reports-production', 'reports', 'Production', 'production', 'Clapperboard', 3, 'table', 'Production reports', '#16a34a'),
    createTab('reports-financial', 'reports', 'Financial', 'financial', 'DollarSign', 4, 'table', 'Financial reports', '#059669'),
    createTab('reports-crew', 'reports', 'Crew', 'crew', 'Users', 5, 'table', 'Crew & personnel reports', '#8b5cf6'),
    createTab('reports-assets', 'reports', 'Assets', 'assets', 'Package', 6, 'table', 'Asset & equipment reports', '#ea580c'),
    createTab('reports-scheduled', 'reports', 'Scheduled', 'scheduled', 'Calendar', 7, 'calendar', 'Scheduled report delivery', '#dc2626'),
    createTab('reports-exports', 'reports', 'Exports', 'exports', 'Download', 8, 'table', 'Exported reports & files', '#0891b2'),
    createTab('reports-insights', 'reports', 'Insights', 'insights', 'TrendingUp', 9, 'dashboard', 'Data insights & recommendations', '#f59e0b'),
  ],
  analytics: [
    createTab('analytics-overview', 'analytics', 'Overview', 'overview', 'LayoutDashboard', 0, 'dashboard', 'Analytics overview & key metrics', '#7c3aed'),
    createTab('analytics-production', 'analytics', 'Production', 'production', 'Clapperboard', 1, 'dashboard', 'Production performance analytics', '#16a34a'),
    createTab('analytics-financial', 'analytics', 'Financial', 'financial', 'DollarSign', 2, 'dashboard', 'Financial performance analytics', '#059669'),
    createTab('analytics-crew', 'analytics', 'Crew', 'crew', 'Users', 3, 'dashboard', 'Crew productivity & utilization', '#2563eb'),
    createTab('analytics-timeline', 'analytics', 'Timeline', 'timeline', 'LineChart', 4, 'timeline', 'Trends over time', '#0891b2'),
    createTab('analytics-comparisons', 'analytics', 'Comparisons', 'comparisons', 'BarChart2', 5, 'pivot', 'Compare productions & projects', '#8b5cf6'),
    createTab('analytics-kpi', 'analytics', 'KPI', 'kpi', 'Target', 6, 'dashboard', 'Key performance indicators', '#dc2626'),
    createTab('analytics-forecasting', 'analytics', 'Forecasting', 'forecasting', 'TrendingUp', 7, 'dashboard', 'Predictive analytics & forecasts', '#f59e0b'),
    createTab('analytics-custom', 'analytics', 'Custom', 'custom', 'Sliders', 8, 'pivot', 'Custom analytics views', '#7c3aed'),
    createTab('analytics-realtime', 'analytics', 'Real-time', 'realtime', 'Activity', 9, 'activity', 'Live metrics & monitoring', '#16a34a'),
  ],
  goals: [
    createTab('goals-overview', 'goals', 'Overview', 'overview', 'LayoutDashboard', 0, 'dashboard', 'Goals overview & progress', '#10b981'),
    createTab('goals-my-goals', 'goals', 'My Goals', 'my-goals', 'Target', 1, 'list', 'Your personal goals & objectives', '#2563eb'),
    createTab('goals-team-goals', 'goals', 'Team Goals', 'team-goals', 'Users', 2, 'table', 'Team & department goals', '#7c3aed'),
    createTab('goals-company-goals', 'goals', 'Company Goals', 'company-goals', 'Building2', 3, 'table', 'Organization-wide objectives', '#8b5cf6'),
    createTab('goals-okrs', 'goals', 'OKRs', 'okrs', 'Crosshair', 4, 'table', 'Objectives & key results', '#ea580c'),
    createTab('goals-milestones', 'goals', 'Milestones', 'milestones', 'Flag', 5, 'timeline', 'Key milestones & achievements', '#16a34a'),
    createTab('goals-progress', 'goals', 'Progress', 'progress', 'TrendingUp', 6, 'dashboard', 'Goal progress tracking', '#059669'),
    createTab('goals-reviews', 'goals', 'Reviews', 'reviews', 'FileCheck', 7, 'calendar', 'Goal review cycles', '#0891b2'),
    createTab('goals-insights', 'goals', 'Insights', 'insights', 'Lightbulb', 8, 'dashboard', 'Performance insights & trends', '#f59e0b'),
    createTab('goals-archive', 'goals', 'Archive', 'archive', 'Archive', 9, 'table', 'Completed & archived goals', '#64748b'),
  ],
}

export function getModuleTabs(moduleId: string): ModuleTab[] {
  return MODULE_TABS[moduleId] || []
}

export function getTabBySlug(moduleId: string, tabSlug: string): ModuleTab | undefined {
  const tabs = MODULE_TABS[moduleId] || []
  return tabs.find((tab) => tab.slug === tabSlug)
}
